// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s2clientprotocol/error.proto

package SC2APIProtocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ActionResult int32

const (
	ActionResult_Success                             ActionResult = 1
	ActionResult_NotSupported                        ActionResult = 2
	ActionResult_Error                               ActionResult = 3
	ActionResult_CantQueueThatOrder                  ActionResult = 4
	ActionResult_Retry                               ActionResult = 5
	ActionResult_Cooldown                            ActionResult = 6
	ActionResult_QueueIsFull                         ActionResult = 7
	ActionResult_RallyQueueIsFull                    ActionResult = 8
	ActionResult_NotEnoughMinerals                   ActionResult = 9
	ActionResult_NotEnoughVespene                    ActionResult = 10
	ActionResult_NotEnoughTerrazine                  ActionResult = 11
	ActionResult_NotEnoughCustom                     ActionResult = 12
	ActionResult_NotEnoughFood                       ActionResult = 13
	ActionResult_FoodUsageImpossible                 ActionResult = 14
	ActionResult_NotEnoughLife                       ActionResult = 15
	ActionResult_NotEnoughShields                    ActionResult = 16
	ActionResult_NotEnoughEnergy                     ActionResult = 17
	ActionResult_LifeSuppressed                      ActionResult = 18
	ActionResult_ShieldsSuppressed                   ActionResult = 19
	ActionResult_EnergySuppressed                    ActionResult = 20
	ActionResult_NotEnoughCharges                    ActionResult = 21
	ActionResult_CantAddMoreCharges                  ActionResult = 22
	ActionResult_TooMuchMinerals                     ActionResult = 23
	ActionResult_TooMuchVespene                      ActionResult = 24
	ActionResult_TooMuchTerrazine                    ActionResult = 25
	ActionResult_TooMuchCustom                       ActionResult = 26
	ActionResult_TooMuchFood                         ActionResult = 27
	ActionResult_TooMuchLife                         ActionResult = 28
	ActionResult_TooMuchShields                      ActionResult = 29
	ActionResult_TooMuchEnergy                       ActionResult = 30
	ActionResult_MustTargetUnitWithLife              ActionResult = 31
	ActionResult_MustTargetUnitWithShields           ActionResult = 32
	ActionResult_MustTargetUnitWithEnergy            ActionResult = 33
	ActionResult_CantTrade                           ActionResult = 34
	ActionResult_CantSpend                           ActionResult = 35
	ActionResult_CantTargetThatUnit                  ActionResult = 36
	ActionResult_CouldntAllocateUnit                 ActionResult = 37
	ActionResult_UnitCantMove                        ActionResult = 38
	ActionResult_TransportIsHoldingPosition          ActionResult = 39
	ActionResult_BuildTechRequirementsNotMet         ActionResult = 40
	ActionResult_CantFindPlacementLocation           ActionResult = 41
	ActionResult_CantBuildOnThat                     ActionResult = 42
	ActionResult_CantBuildTooCloseToDropOff          ActionResult = 43
	ActionResult_CantBuildLocationInvalid            ActionResult = 44
	ActionResult_CantSeeBuildLocation                ActionResult = 45
	ActionResult_CantBuildTooCloseToCreepSource      ActionResult = 46
	ActionResult_CantBuildTooCloseToResources        ActionResult = 47
	ActionResult_CantBuildTooFarFromWater            ActionResult = 48
	ActionResult_CantBuildTooFarFromCreepSource      ActionResult = 49
	ActionResult_CantBuildTooFarFromBuildPowerSource ActionResult = 50
	ActionResult_CantBuildOnDenseTerrain             ActionResult = 51
	ActionResult_CantTrainTooFarFromTrainPowerSource ActionResult = 52
	ActionResult_CantLandLocationInvalid             ActionResult = 53
	ActionResult_CantSeeLandLocation                 ActionResult = 54
	ActionResult_CantLandTooCloseToCreepSource       ActionResult = 55
	ActionResult_CantLandTooCloseToResources         ActionResult = 56
	ActionResult_CantLandTooFarFromWater             ActionResult = 57
	ActionResult_CantLandTooFarFromCreepSource       ActionResult = 58
	ActionResult_CantLandTooFarFromBuildPowerSource  ActionResult = 59
	ActionResult_CantLandTooFarFromTrainPowerSource  ActionResult = 60
	ActionResult_CantLandOnDenseTerrain              ActionResult = 61
	ActionResult_AddOnTooFarFromBuilding             ActionResult = 62
	ActionResult_MustBuildRefineryFirst              ActionResult = 63
	ActionResult_BuildingIsUnderConstruction         ActionResult = 64
	ActionResult_CantFindDropOff                     ActionResult = 65
	ActionResult_CantLoadOtherPlayersUnits           ActionResult = 66
	ActionResult_NotEnoughRoomToLoadUnit             ActionResult = 67
	ActionResult_CantUnloadUnitsThere                ActionResult = 68
	ActionResult_CantWarpInUnitsThere                ActionResult = 69
	ActionResult_CantLoadImmobileUnits               ActionResult = 70
	ActionResult_CantRechargeImmobileUnits           ActionResult = 71
	ActionResult_CantRechargeUnderConstructionUnits  ActionResult = 72
	ActionResult_CantLoadThatUnit                    ActionResult = 73
	ActionResult_NoCargoToUnload                     ActionResult = 74
	ActionResult_LoadAllNoTargetsFound               ActionResult = 75
	ActionResult_NotWhileOccupied                    ActionResult = 76
	ActionResult_CantAttackWithoutAmmo               ActionResult = 77
	ActionResult_CantHoldAnyMoreAmmo                 ActionResult = 78
	ActionResult_TechRequirementsNotMet              ActionResult = 79
	ActionResult_MustLockdownUnitFirst               ActionResult = 80
	ActionResult_MustTargetUnit                      ActionResult = 81
	ActionResult_MustTargetInventory                 ActionResult = 82
	ActionResult_MustTargetVisibleUnit               ActionResult = 83
	ActionResult_MustTargetVisibleLocation           ActionResult = 84
	ActionResult_MustTargetWalkableLocation          ActionResult = 85
	ActionResult_MustTargetPawnableUnit              ActionResult = 86
	ActionResult_YouCantControlThatUnit              ActionResult = 87
	ActionResult_YouCantIssueCommandsToThatUnit      ActionResult = 88
	ActionResult_MustTargetResources                 ActionResult = 89
	ActionResult_RequiresHealTarget                  ActionResult = 90
	ActionResult_RequiresRepairTarget                ActionResult = 91
	ActionResult_NoItemsToDrop                       ActionResult = 92
	ActionResult_CantHoldAnyMoreItems                ActionResult = 93
	ActionResult_CantHoldThat                        ActionResult = 94
	ActionResult_TargetHasNoInventory                ActionResult = 95
	ActionResult_CantDropThisItem                    ActionResult = 96
	ActionResult_CantMoveThisItem                    ActionResult = 97
	ActionResult_CantPawnThisUnit                    ActionResult = 98
	ActionResult_MustTargetCaster                    ActionResult = 99
	ActionResult_CantTargetCaster                    ActionResult = 100
	ActionResult_MustTargetOuter                     ActionResult = 101
	ActionResult_CantTargetOuter                     ActionResult = 102
	ActionResult_MustTargetYourOwnUnits              ActionResult = 103
	ActionResult_CantTargetYourOwnUnits              ActionResult = 104
	ActionResult_MustTargetFriendlyUnits             ActionResult = 105
	ActionResult_CantTargetFriendlyUnits             ActionResult = 106
	ActionResult_MustTargetNeutralUnits              ActionResult = 107
	ActionResult_CantTargetNeutralUnits              ActionResult = 108
	ActionResult_MustTargetEnemyUnits                ActionResult = 109
	ActionResult_CantTargetEnemyUnits                ActionResult = 110
	ActionResult_MustTargetAirUnits                  ActionResult = 111
	ActionResult_CantTargetAirUnits                  ActionResult = 112
	ActionResult_MustTargetGroundUnits               ActionResult = 113
	ActionResult_CantTargetGroundUnits               ActionResult = 114
	ActionResult_MustTargetStructures                ActionResult = 115
	ActionResult_CantTargetStructures                ActionResult = 116
	ActionResult_MustTargetLightUnits                ActionResult = 117
	ActionResult_CantTargetLightUnits                ActionResult = 118
	ActionResult_MustTargetArmoredUnits              ActionResult = 119
	ActionResult_CantTargetArmoredUnits              ActionResult = 120
	ActionResult_MustTargetBiologicalUnits           ActionResult = 121
	ActionResult_CantTargetBiologicalUnits           ActionResult = 122
	ActionResult_MustTargetHeroicUnits               ActionResult = 123
	ActionResult_CantTargetHeroicUnits               ActionResult = 124
	ActionResult_MustTargetRoboticUnits              ActionResult = 125
	ActionResult_CantTargetRoboticUnits              ActionResult = 126
	ActionResult_MustTargetMechanicalUnits           ActionResult = 127
	ActionResult_CantTargetMechanicalUnits           ActionResult = 128
	ActionResult_MustTargetPsionicUnits              ActionResult = 129
	ActionResult_CantTargetPsionicUnits              ActionResult = 130
	ActionResult_MustTargetMassiveUnits              ActionResult = 131
	ActionResult_CantTargetMassiveUnits              ActionResult = 132
	ActionResult_MustTargetMissile                   ActionResult = 133
	ActionResult_CantTargetMissile                   ActionResult = 134
	ActionResult_MustTargetWorkerUnits               ActionResult = 135
	ActionResult_CantTargetWorkerUnits               ActionResult = 136
	ActionResult_MustTargetEnergyCapableUnits        ActionResult = 137
	ActionResult_CantTargetEnergyCapableUnits        ActionResult = 138
	ActionResult_MustTargetShieldCapableUnits        ActionResult = 139
	ActionResult_CantTargetShieldCapableUnits        ActionResult = 140
	ActionResult_MustTargetFlyers                    ActionResult = 141
	ActionResult_CantTargetFlyers                    ActionResult = 142
	ActionResult_MustTargetBuriedUnits               ActionResult = 143
	ActionResult_CantTargetBuriedUnits               ActionResult = 144
	ActionResult_MustTargetCloakedUnits              ActionResult = 145
	ActionResult_CantTargetCloakedUnits              ActionResult = 146
	ActionResult_MustTargetUnitsInAStasisField       ActionResult = 147
	ActionResult_CantTargetUnitsInAStasisField       ActionResult = 148
	ActionResult_MustTargetUnderConstructionUnits    ActionResult = 149
	ActionResult_CantTargetUnderConstructionUnits    ActionResult = 150
	ActionResult_MustTargetDeadUnits                 ActionResult = 151
	ActionResult_CantTargetDeadUnits                 ActionResult = 152
	ActionResult_MustTargetRevivableUnits            ActionResult = 153
	ActionResult_CantTargetRevivableUnits            ActionResult = 154
	ActionResult_MustTargetHiddenUnits               ActionResult = 155
	ActionResult_CantTargetHiddenUnits               ActionResult = 156
	ActionResult_CantRechargeOtherPlayersUnits       ActionResult = 157
	ActionResult_MustTargetHallucinations            ActionResult = 158
	ActionResult_CantTargetHallucinations            ActionResult = 159
	ActionResult_MustTargetInvulnerableUnits         ActionResult = 160
	ActionResult_CantTargetInvulnerableUnits         ActionResult = 161
	ActionResult_MustTargetDetectedUnits             ActionResult = 162
	ActionResult_CantTargetDetectedUnits             ActionResult = 163
	ActionResult_CantTargetUnitWithEnergy            ActionResult = 164
	ActionResult_CantTargetUnitWithShields           ActionResult = 165
	ActionResult_MustTargetUncommandableUnits        ActionResult = 166
	ActionResult_CantTargetUncommandableUnits        ActionResult = 167
	ActionResult_MustTargetPreventDefeatUnits        ActionResult = 168
	ActionResult_CantTargetPreventDefeatUnits        ActionResult = 169
	ActionResult_MustTargetPreventRevealUnits        ActionResult = 170
	ActionResult_CantTargetPreventRevealUnits        ActionResult = 171
	ActionResult_MustTargetPassiveUnits              ActionResult = 172
	ActionResult_CantTargetPassiveUnits              ActionResult = 173
	ActionResult_MustTargetStunnedUnits              ActionResult = 174
	ActionResult_CantTargetStunnedUnits              ActionResult = 175
	ActionResult_MustTargetSummonedUnits             ActionResult = 176
	ActionResult_CantTargetSummonedUnits             ActionResult = 177
	ActionResult_MustTargetUser1                     ActionResult = 178
	ActionResult_CantTargetUser1                     ActionResult = 179
	ActionResult_MustTargetUnstoppableUnits          ActionResult = 180
	ActionResult_CantTargetUnstoppableUnits          ActionResult = 181
	ActionResult_MustTargetResistantUnits            ActionResult = 182
	ActionResult_CantTargetResistantUnits            ActionResult = 183
	ActionResult_MustTargetDazedUnits                ActionResult = 184
	ActionResult_CantTargetDazedUnits                ActionResult = 185
	ActionResult_CantLockdown                        ActionResult = 186
	ActionResult_CantMindControl                     ActionResult = 187
	ActionResult_MustTargetDestructibles             ActionResult = 188
	ActionResult_CantTargetDestructibles             ActionResult = 189
	ActionResult_MustTargetItems                     ActionResult = 190
	ActionResult_CantTargetItems                     ActionResult = 191
	ActionResult_NoCalldownAvailable                 ActionResult = 192
	ActionResult_WaypointListFull                    ActionResult = 193
	ActionResult_MustTargetRace                      ActionResult = 194
	ActionResult_CantTargetRace                      ActionResult = 195
	ActionResult_MustTargetSimilarUnits              ActionResult = 196
	ActionResult_CantTargetSimilarUnits              ActionResult = 197
	ActionResult_CantFindEnoughTargets               ActionResult = 198
	ActionResult_AlreadySpawningLarva                ActionResult = 199
	ActionResult_CantTargetExhaustedResources        ActionResult = 200
	ActionResult_CantUseMinimap                      ActionResult = 201
	ActionResult_CantUseInfoPanel                    ActionResult = 202
	ActionResult_OrderQueueIsFull                    ActionResult = 203
	ActionResult_CantHarvestThatResource             ActionResult = 204
	ActionResult_HarvestersNotRequired               ActionResult = 205
	ActionResult_AlreadyTargeted                     ActionResult = 206
	ActionResult_CantAttackWeaponsDisabled           ActionResult = 207
	ActionResult_CouldntReachTarget                  ActionResult = 208
	ActionResult_TargetIsOutOfRange                  ActionResult = 209
	ActionResult_TargetIsTooClose                    ActionResult = 210
	ActionResult_TargetIsOutOfArc                    ActionResult = 211
	ActionResult_CantFindTeleportLocation            ActionResult = 212
	ActionResult_InvalidItemClass                    ActionResult = 213
	ActionResult_CantFindCancelOrder                 ActionResult = 214
)

var ActionResult_name = map[int32]string{
	1:   "Success",
	2:   "NotSupported",
	3:   "Error",
	4:   "CantQueueThatOrder",
	5:   "Retry",
	6:   "Cooldown",
	7:   "QueueIsFull",
	8:   "RallyQueueIsFull",
	9:   "NotEnoughMinerals",
	10:  "NotEnoughVespene",
	11:  "NotEnoughTerrazine",
	12:  "NotEnoughCustom",
	13:  "NotEnoughFood",
	14:  "FoodUsageImpossible",
	15:  "NotEnoughLife",
	16:  "NotEnoughShields",
	17:  "NotEnoughEnergy",
	18:  "LifeSuppressed",
	19:  "ShieldsSuppressed",
	20:  "EnergySuppressed",
	21:  "NotEnoughCharges",
	22:  "CantAddMoreCharges",
	23:  "TooMuchMinerals",
	24:  "TooMuchVespene",
	25:  "TooMuchTerrazine",
	26:  "TooMuchCustom",
	27:  "TooMuchFood",
	28:  "TooMuchLife",
	29:  "TooMuchShields",
	30:  "TooMuchEnergy",
	31:  "MustTargetUnitWithLife",
	32:  "MustTargetUnitWithShields",
	33:  "MustTargetUnitWithEnergy",
	34:  "CantTrade",
	35:  "CantSpend",
	36:  "CantTargetThatUnit",
	37:  "CouldntAllocateUnit",
	38:  "UnitCantMove",
	39:  "TransportIsHoldingPosition",
	40:  "BuildTechRequirementsNotMet",
	41:  "CantFindPlacementLocation",
	42:  "CantBuildOnThat",
	43:  "CantBuildTooCloseToDropOff",
	44:  "CantBuildLocationInvalid",
	45:  "CantSeeBuildLocation",
	46:  "CantBuildTooCloseToCreepSource",
	47:  "CantBuildTooCloseToResources",
	48:  "CantBuildTooFarFromWater",
	49:  "CantBuildTooFarFromCreepSource",
	50:  "CantBuildTooFarFromBuildPowerSource",
	51:  "CantBuildOnDenseTerrain",
	52:  "CantTrainTooFarFromTrainPowerSource",
	53:  "CantLandLocationInvalid",
	54:  "CantSeeLandLocation",
	55:  "CantLandTooCloseToCreepSource",
	56:  "CantLandTooCloseToResources",
	57:  "CantLandTooFarFromWater",
	58:  "CantLandTooFarFromCreepSource",
	59:  "CantLandTooFarFromBuildPowerSource",
	60:  "CantLandTooFarFromTrainPowerSource",
	61:  "CantLandOnDenseTerrain",
	62:  "AddOnTooFarFromBuilding",
	63:  "MustBuildRefineryFirst",
	64:  "BuildingIsUnderConstruction",
	65:  "CantFindDropOff",
	66:  "CantLoadOtherPlayersUnits",
	67:  "NotEnoughRoomToLoadUnit",
	68:  "CantUnloadUnitsThere",
	69:  "CantWarpInUnitsThere",
	70:  "CantLoadImmobileUnits",
	71:  "CantRechargeImmobileUnits",
	72:  "CantRechargeUnderConstructionUnits",
	73:  "CantLoadThatUnit",
	74:  "NoCargoToUnload",
	75:  "LoadAllNoTargetsFound",
	76:  "NotWhileOccupied",
	77:  "CantAttackWithoutAmmo",
	78:  "CantHoldAnyMoreAmmo",
	79:  "TechRequirementsNotMet",
	80:  "MustLockdownUnitFirst",
	81:  "MustTargetUnit",
	82:  "MustTargetInventory",
	83:  "MustTargetVisibleUnit",
	84:  "MustTargetVisibleLocation",
	85:  "MustTargetWalkableLocation",
	86:  "MustTargetPawnableUnit",
	87:  "YouCantControlThatUnit",
	88:  "YouCantIssueCommandsToThatUnit",
	89:  "MustTargetResources",
	90:  "RequiresHealTarget",
	91:  "RequiresRepairTarget",
	92:  "NoItemsToDrop",
	93:  "CantHoldAnyMoreItems",
	94:  "CantHoldThat",
	95:  "TargetHasNoInventory",
	96:  "CantDropThisItem",
	97:  "CantMoveThisItem",
	98:  "CantPawnThisUnit",
	99:  "MustTargetCaster",
	100: "CantTargetCaster",
	101: "MustTargetOuter",
	102: "CantTargetOuter",
	103: "MustTargetYourOwnUnits",
	104: "CantTargetYourOwnUnits",
	105: "MustTargetFriendlyUnits",
	106: "CantTargetFriendlyUnits",
	107: "MustTargetNeutralUnits",
	108: "CantTargetNeutralUnits",
	109: "MustTargetEnemyUnits",
	110: "CantTargetEnemyUnits",
	111: "MustTargetAirUnits",
	112: "CantTargetAirUnits",
	113: "MustTargetGroundUnits",
	114: "CantTargetGroundUnits",
	115: "MustTargetStructures",
	116: "CantTargetStructures",
	117: "MustTargetLightUnits",
	118: "CantTargetLightUnits",
	119: "MustTargetArmoredUnits",
	120: "CantTargetArmoredUnits",
	121: "MustTargetBiologicalUnits",
	122: "CantTargetBiologicalUnits",
	123: "MustTargetHeroicUnits",
	124: "CantTargetHeroicUnits",
	125: "MustTargetRoboticUnits",
	126: "CantTargetRoboticUnits",
	127: "MustTargetMechanicalUnits",
	128: "CantTargetMechanicalUnits",
	129: "MustTargetPsionicUnits",
	130: "CantTargetPsionicUnits",
	131: "MustTargetMassiveUnits",
	132: "CantTargetMassiveUnits",
	133: "MustTargetMissile",
	134: "CantTargetMissile",
	135: "MustTargetWorkerUnits",
	136: "CantTargetWorkerUnits",
	137: "MustTargetEnergyCapableUnits",
	138: "CantTargetEnergyCapableUnits",
	139: "MustTargetShieldCapableUnits",
	140: "CantTargetShieldCapableUnits",
	141: "MustTargetFlyers",
	142: "CantTargetFlyers",
	143: "MustTargetBuriedUnits",
	144: "CantTargetBuriedUnits",
	145: "MustTargetCloakedUnits",
	146: "CantTargetCloakedUnits",
	147: "MustTargetUnitsInAStasisField",
	148: "CantTargetUnitsInAStasisField",
	149: "MustTargetUnderConstructionUnits",
	150: "CantTargetUnderConstructionUnits",
	151: "MustTargetDeadUnits",
	152: "CantTargetDeadUnits",
	153: "MustTargetRevivableUnits",
	154: "CantTargetRevivableUnits",
	155: "MustTargetHiddenUnits",
	156: "CantTargetHiddenUnits",
	157: "CantRechargeOtherPlayersUnits",
	158: "MustTargetHallucinations",
	159: "CantTargetHallucinations",
	160: "MustTargetInvulnerableUnits",
	161: "CantTargetInvulnerableUnits",
	162: "MustTargetDetectedUnits",
	163: "CantTargetDetectedUnits",
	164: "CantTargetUnitWithEnergy",
	165: "CantTargetUnitWithShields",
	166: "MustTargetUncommandableUnits",
	167: "CantTargetUncommandableUnits",
	168: "MustTargetPreventDefeatUnits",
	169: "CantTargetPreventDefeatUnits",
	170: "MustTargetPreventRevealUnits",
	171: "CantTargetPreventRevealUnits",
	172: "MustTargetPassiveUnits",
	173: "CantTargetPassiveUnits",
	174: "MustTargetStunnedUnits",
	175: "CantTargetStunnedUnits",
	176: "MustTargetSummonedUnits",
	177: "CantTargetSummonedUnits",
	178: "MustTargetUser1",
	179: "CantTargetUser1",
	180: "MustTargetUnstoppableUnits",
	181: "CantTargetUnstoppableUnits",
	182: "MustTargetResistantUnits",
	183: "CantTargetResistantUnits",
	184: "MustTargetDazedUnits",
	185: "CantTargetDazedUnits",
	186: "CantLockdown",
	187: "CantMindControl",
	188: "MustTargetDestructibles",
	189: "CantTargetDestructibles",
	190: "MustTargetItems",
	191: "CantTargetItems",
	192: "NoCalldownAvailable",
	193: "WaypointListFull",
	194: "MustTargetRace",
	195: "CantTargetRace",
	196: "MustTargetSimilarUnits",
	197: "CantTargetSimilarUnits",
	198: "CantFindEnoughTargets",
	199: "AlreadySpawningLarva",
	200: "CantTargetExhaustedResources",
	201: "CantUseMinimap",
	202: "CantUseInfoPanel",
	203: "OrderQueueIsFull",
	204: "CantHarvestThatResource",
	205: "HarvestersNotRequired",
	206: "AlreadyTargeted",
	207: "CantAttackWeaponsDisabled",
	208: "CouldntReachTarget",
	209: "TargetIsOutOfRange",
	210: "TargetIsTooClose",
	211: "TargetIsOutOfArc",
	212: "CantFindTeleportLocation",
	213: "InvalidItemClass",
	214: "CantFindCancelOrder",
}
var ActionResult_value = map[string]int32{
	"Success":                             1,
	"NotSupported":                        2,
	"Error":                               3,
	"CantQueueThatOrder":                  4,
	"Retry":                               5,
	"Cooldown":                            6,
	"QueueIsFull":                         7,
	"RallyQueueIsFull":                    8,
	"NotEnoughMinerals":                   9,
	"NotEnoughVespene":                    10,
	"NotEnoughTerrazine":                  11,
	"NotEnoughCustom":                     12,
	"NotEnoughFood":                       13,
	"FoodUsageImpossible":                 14,
	"NotEnoughLife":                       15,
	"NotEnoughShields":                    16,
	"NotEnoughEnergy":                     17,
	"LifeSuppressed":                      18,
	"ShieldsSuppressed":                   19,
	"EnergySuppressed":                    20,
	"NotEnoughCharges":                    21,
	"CantAddMoreCharges":                  22,
	"TooMuchMinerals":                     23,
	"TooMuchVespene":                      24,
	"TooMuchTerrazine":                    25,
	"TooMuchCustom":                       26,
	"TooMuchFood":                         27,
	"TooMuchLife":                         28,
	"TooMuchShields":                      29,
	"TooMuchEnergy":                       30,
	"MustTargetUnitWithLife":              31,
	"MustTargetUnitWithShields":           32,
	"MustTargetUnitWithEnergy":            33,
	"CantTrade":                           34,
	"CantSpend":                           35,
	"CantTargetThatUnit":                  36,
	"CouldntAllocateUnit":                 37,
	"UnitCantMove":                        38,
	"TransportIsHoldingPosition":          39,
	"BuildTechRequirementsNotMet":         40,
	"CantFindPlacementLocation":           41,
	"CantBuildOnThat":                     42,
	"CantBuildTooCloseToDropOff":          43,
	"CantBuildLocationInvalid":            44,
	"CantSeeBuildLocation":                45,
	"CantBuildTooCloseToCreepSource":      46,
	"CantBuildTooCloseToResources":        47,
	"CantBuildTooFarFromWater":            48,
	"CantBuildTooFarFromCreepSource":      49,
	"CantBuildTooFarFromBuildPowerSource": 50,
	"CantBuildOnDenseTerrain":             51,
	"CantTrainTooFarFromTrainPowerSource": 52,
	"CantLandLocationInvalid":             53,
	"CantSeeLandLocation":                 54,
	"CantLandTooCloseToCreepSource":       55,
	"CantLandTooCloseToResources":         56,
	"CantLandTooFarFromWater":             57,
	"CantLandTooFarFromCreepSource":       58,
	"CantLandTooFarFromBuildPowerSource":  59,
	"CantLandTooFarFromTrainPowerSource":  60,
	"CantLandOnDenseTerrain":              61,
	"AddOnTooFarFromBuilding":             62,
	"MustBuildRefineryFirst":              63,
	"BuildingIsUnderConstruction":         64,
	"CantFindDropOff":                     65,
	"CantLoadOtherPlayersUnits":           66,
	"NotEnoughRoomToLoadUnit":             67,
	"CantUnloadUnitsThere":                68,
	"CantWarpInUnitsThere":                69,
	"CantLoadImmobileUnits":               70,
	"CantRechargeImmobileUnits":           71,
	"CantRechargeUnderConstructionUnits":  72,
	"CantLoadThatUnit":                    73,
	"NoCargoToUnload":                     74,
	"LoadAllNoTargetsFound":               75,
	"NotWhileOccupied":                    76,
	"CantAttackWithoutAmmo":               77,
	"CantHoldAnyMoreAmmo":                 78,
	"TechRequirementsNotMet":              79,
	"MustLockdownUnitFirst":               80,
	"MustTargetUnit":                      81,
	"MustTargetInventory":                 82,
	"MustTargetVisibleUnit":               83,
	"MustTargetVisibleLocation":           84,
	"MustTargetWalkableLocation":          85,
	"MustTargetPawnableUnit":              86,
	"YouCantControlThatUnit":              87,
	"YouCantIssueCommandsToThatUnit":      88,
	"MustTargetResources":                 89,
	"RequiresHealTarget":                  90,
	"RequiresRepairTarget":                91,
	"NoItemsToDrop":                       92,
	"CantHoldAnyMoreItems":                93,
	"CantHoldThat":                        94,
	"TargetHasNoInventory":                95,
	"CantDropThisItem":                    96,
	"CantMoveThisItem":                    97,
	"CantPawnThisUnit":                    98,
	"MustTargetCaster":                    99,
	"CantTargetCaster":                    100,
	"MustTargetOuter":                     101,
	"CantTargetOuter":                     102,
	"MustTargetYourOwnUnits":              103,
	"CantTargetYourOwnUnits":              104,
	"MustTargetFriendlyUnits":             105,
	"CantTargetFriendlyUnits":             106,
	"MustTargetNeutralUnits":              107,
	"CantTargetNeutralUnits":              108,
	"MustTargetEnemyUnits":                109,
	"CantTargetEnemyUnits":                110,
	"MustTargetAirUnits":                  111,
	"CantTargetAirUnits":                  112,
	"MustTargetGroundUnits":               113,
	"CantTargetGroundUnits":               114,
	"MustTargetStructures":                115,
	"CantTargetStructures":                116,
	"MustTargetLightUnits":                117,
	"CantTargetLightUnits":                118,
	"MustTargetArmoredUnits":              119,
	"CantTargetArmoredUnits":              120,
	"MustTargetBiologicalUnits":           121,
	"CantTargetBiologicalUnits":           122,
	"MustTargetHeroicUnits":               123,
	"CantTargetHeroicUnits":               124,
	"MustTargetRoboticUnits":              125,
	"CantTargetRoboticUnits":              126,
	"MustTargetMechanicalUnits":           127,
	"CantTargetMechanicalUnits":           128,
	"MustTargetPsionicUnits":              129,
	"CantTargetPsionicUnits":              130,
	"MustTargetMassiveUnits":              131,
	"CantTargetMassiveUnits":              132,
	"MustTargetMissile":                   133,
	"CantTargetMissile":                   134,
	"MustTargetWorkerUnits":               135,
	"CantTargetWorkerUnits":               136,
	"MustTargetEnergyCapableUnits":        137,
	"CantTargetEnergyCapableUnits":        138,
	"MustTargetShieldCapableUnits":        139,
	"CantTargetShieldCapableUnits":        140,
	"MustTargetFlyers":                    141,
	"CantTargetFlyers":                    142,
	"MustTargetBuriedUnits":               143,
	"CantTargetBuriedUnits":               144,
	"MustTargetCloakedUnits":              145,
	"CantTargetCloakedUnits":              146,
	"MustTargetUnitsInAStasisField":       147,
	"CantTargetUnitsInAStasisField":       148,
	"MustTargetUnderConstructionUnits":    149,
	"CantTargetUnderConstructionUnits":    150,
	"MustTargetDeadUnits":                 151,
	"CantTargetDeadUnits":                 152,
	"MustTargetRevivableUnits":            153,
	"CantTargetRevivableUnits":            154,
	"MustTargetHiddenUnits":               155,
	"CantTargetHiddenUnits":               156,
	"CantRechargeOtherPlayersUnits":       157,
	"MustTargetHallucinations":            158,
	"CantTargetHallucinations":            159,
	"MustTargetInvulnerableUnits":         160,
	"CantTargetInvulnerableUnits":         161,
	"MustTargetDetectedUnits":             162,
	"CantTargetDetectedUnits":             163,
	"CantTargetUnitWithEnergy":            164,
	"CantTargetUnitWithShields":           165,
	"MustTargetUncommandableUnits":        166,
	"CantTargetUncommandableUnits":        167,
	"MustTargetPreventDefeatUnits":        168,
	"CantTargetPreventDefeatUnits":        169,
	"MustTargetPreventRevealUnits":        170,
	"CantTargetPreventRevealUnits":        171,
	"MustTargetPassiveUnits":              172,
	"CantTargetPassiveUnits":              173,
	"MustTargetStunnedUnits":              174,
	"CantTargetStunnedUnits":              175,
	"MustTargetSummonedUnits":             176,
	"CantTargetSummonedUnits":             177,
	"MustTargetUser1":                     178,
	"CantTargetUser1":                     179,
	"MustTargetUnstoppableUnits":          180,
	"CantTargetUnstoppableUnits":          181,
	"MustTargetResistantUnits":            182,
	"CantTargetResistantUnits":            183,
	"MustTargetDazedUnits":                184,
	"CantTargetDazedUnits":                185,
	"CantLockdown":                        186,
	"CantMindControl":                     187,
	"MustTargetDestructibles":             188,
	"CantTargetDestructibles":             189,
	"MustTargetItems":                     190,
	"CantTargetItems":                     191,
	"NoCalldownAvailable":                 192,
	"WaypointListFull":                    193,
	"MustTargetRace":                      194,
	"CantTargetRace":                      195,
	"MustTargetSimilarUnits":              196,
	"CantTargetSimilarUnits":              197,
	"CantFindEnoughTargets":               198,
	"AlreadySpawningLarva":                199,
	"CantTargetExhaustedResources":        200,
	"CantUseMinimap":                      201,
	"CantUseInfoPanel":                    202,
	"OrderQueueIsFull":                    203,
	"CantHarvestThatResource":             204,
	"HarvestersNotRequired":               205,
	"AlreadyTargeted":                     206,
	"CantAttackWeaponsDisabled":           207,
	"CouldntReachTarget":                  208,
	"TargetIsOutOfRange":                  209,
	"TargetIsTooClose":                    210,
	"TargetIsOutOfArc":                    211,
	"CantFindTeleportLocation":            212,
	"InvalidItemClass":                    213,
	"CantFindCancelOrder":                 214,
}

func (x ActionResult) Enum() *ActionResult {
	p := new(ActionResult)
	*p = x
	return p
}
func (x ActionResult) String() string {
	return proto.EnumName(ActionResult_name, int32(x))
}
func (x *ActionResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActionResult_value, data, "ActionResult")
	if err != nil {
		return err
	}
	*x = ActionResult(value)
	return nil
}
func (ActionResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func init() {
	proto.RegisterEnum("SC2APIProtocol.ActionResult", ActionResult_name, ActionResult_value)
}

func init() { proto.RegisterFile("s2clientprotocol/error.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 2197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x58, 0xf7, 0x9b, 0x1b, 0xb7,
	0x11, 0xfd, 0x98, 0xc4, 0xb1, 0xbd, 0x96, 0x25, 0x08, 0xea, 0xd2, 0xa9, 0x3a, 0xb6, 0x13, 0x27,
	0xb6, 0x63, 0xa5, 0xf7, 0x50, 0x3c, 0xd1, 0xc7, 0xe4, 0x78, 0x77, 0x26, 0x79, 0xba, 0x28, 0x1d,
	0xda, 0x9d, 0x23, 0x91, 0x03, 0x01, 0x1a, 0xd8, 0xe5, 0x99, 0x4a, 0xef, 0xbd, 0xf7, 0xde, 0x13,
	0xa7, 0xf7, 0xde, 0x7b, 0xef, 0xe5, 0xef, 0xc9, 0x37, 0xd8, 0xc5, 0x2e, 0xb0, 0x64, 0x7e, 0x23,
	0xe7, 0xcd, 0x0c, 0x06, 0x0f, 0x53, 0x80, 0x8d, 0x96, 0xcc, 0xf9, 0x58, 0x70, 0x90, 0xe9, 0x44,
	0xab, 0x54, 0xc5, 0x4a, 0xdc, 0x09, 0x5a, 0x2b, 0x7d, 0x87, 0xfd, 0x4b, 0xf7, 0xf6, 0x5b, 0xe7,
	0x9b, 0x1b, 0x9d, 0x8d, 0x02, 0xbb, 0xed, 0xfe, 0xdb, 0xa3, 0x3d, 0xcd, 0x38, 0xe5, 0x4a, 0xf6,
	0xc0, 0x64, 0x22, 0xa5, 0x37, 0x44, 0xd7, 0xf6, 0xb3, 0x38, 0x06, 0x63, 0x48, 0x83, 0x92, 0x68,
	0xcf, 0x9a, 0x4a, 0xfb, 0xd9, 0x64, 0xa2, 0x74, 0x0a, 0x09, 0x79, 0x00, 0xbd, 0x3e, 0xba, 0xe6,
	0x22, 0xba, 0x23, 0x0f, 0xa4, 0x87, 0x23, 0xda, 0x62, 0x32, 0xbd, 0x27, 0x83, 0x0c, 0x06, 0x23,
	0x96, 0xae, 0xeb, 0x04, 0x34, 0x79, 0x10, 0xaa, 0xf4, 0x20, 0xd5, 0x33, 0x72, 0x0d, 0xdd, 0x13,
	0x5d, 0xd7, 0x52, 0x4a, 0x24, 0x6a, 0x57, 0x92, 0x07, 0xd3, 0x7d, 0xd1, 0x0d, 0x56, 0xb9, 0x63,
	0xda, 0x99, 0x10, 0xe4, 0x5a, 0x7a, 0x30, 0x22, 0x3d, 0x26, 0xc4, 0xcc, 0x97, 0x5e, 0x47, 0x0f,
	0x45, 0xfb, 0xd7, 0x54, 0x7a, 0x51, 0xaa, 0x6c, 0x38, 0xea, 0x72, 0x09, 0x9a, 0x09, 0x43, 0xae,
	0x47, 0xe5, 0x52, 0x7c, 0x09, 0xcc, 0x04, 0x24, 0x90, 0x08, 0x83, 0x28, 0xa5, 0x03, 0xd0, 0x9a,
	0x5d, 0xe5, 0x12, 0xc8, 0x0d, 0xf4, 0x40, 0xb4, 0xaf, 0x94, 0xb7, 0x32, 0x93, 0xaa, 0x31, 0xd9,
	0x43, 0xf7, 0x47, 0x37, 0x96, 0xc2, 0xb6, 0x52, 0x09, 0xb9, 0x91, 0x1e, 0x89, 0x0e, 0xe0, 0xaf,
	0x4d, 0xc3, 0x86, 0xd0, 0x19, 0x4f, 0x94, 0x31, 0xfc, 0x8a, 0x00, 0xb2, 0x37, 0xd0, 0x5d, 0xe5,
	0xdb, 0x40, 0xf6, 0x05, 0x11, 0xf4, 0x47, 0x1c, 0x44, 0x62, 0x08, 0x09, 0x56, 0xba, 0x28, 0x41,
	0x0f, 0x67, 0x64, 0x3f, 0xa5, 0xd1, 0x5e, 0x34, 0x42, 0xe6, 0x34, 0x18, 0x03, 0x09, 0xa1, 0xb8,
	0xaf, 0xc2, 0xca, 0x13, 0x1f, 0x40, 0xaf, 0xb9, 0x99, 0x27, 0x3d, 0x18, 0xac, 0xd5, 0x1a, 0x31,
	0x3d, 0x04, 0x43, 0x0e, 0x39, 0xca, 0x9b, 0x49, 0xd2, 0x55, 0x1a, 0x9c, 0xfc, 0x30, 0xc6, 0x30,
	0x50, 0xaa, 0x9b, 0xc5, 0x15, 0x61, 0x47, 0x30, 0x86, 0x42, 0xe8, 0xe8, 0x3a, 0x8a, 0x6e, 0x0b,
	0x59, 0x45, 0xd6, 0x31, 0xdc, 0x6b, 0x21, 0x2d, 0xa8, 0x3a, 0x8e, 0x67, 0x55, 0x88, 0x2c, 0x51,
	0x27, 0x3c, 0x81, 0x65, 0x63, 0xc9, 0x73, 0xef, 0xb8, 0x38, 0xe9, 0x39, 0x2a, 0x98, 0x38, 0x45,
	0x8f, 0x47, 0x87, 0xbb, 0x99, 0x49, 0x07, 0x18, 0x6a, 0xba, 0x29, 0x79, 0xba, 0xc5, 0xd3, 0xdc,
	0xc5, 0x69, 0x7a, 0x32, 0x3a, 0x36, 0x8f, 0x39, 0x6f, 0x67, 0xe8, 0x52, 0x74, 0x74, 0x1e, 0x2e,
	0x1c, 0x9f, 0xa5, 0x37, 0x46, 0xd7, 0x23, 0x17, 0x03, 0xcd, 0x12, 0x20, 0xe7, 0xdc, 0xdf, 0xfe,
	0x04, 0x64, 0x42, 0x6e, 0x72, 0x4c, 0xe5, 0xb6, 0x98, 0x9d, 0x68, 0x4f, 0x1e, 0x82, 0xe7, 0xdd,
	0x52, 0x99, 0x48, 0x64, 0xda, 0x14, 0x42, 0xc5, 0x2c, 0x05, 0x0b, 0xdc, 0x8c, 0xa9, 0x8e, 0xbf,
	0xd0, 0xa8, 0xab, 0xa6, 0x40, 0x6e, 0xa1, 0xa7, 0xa2, 0xe3, 0x03, 0xcd, 0xa4, 0xc1, 0xdc, 0xef,
	0x98, 0x15, 0x25, 0x12, 0x2e, 0x87, 0x1b, 0xca, 0x70, 0xac, 0x16, 0x72, 0x2b, 0x3d, 0x1d, 0x9d,
	0xb8, 0x90, 0x71, 0x91, 0x0c, 0x20, 0x1e, 0xf5, 0xe0, 0xde, 0x8c, 0x6b, 0x18, 0x83, 0x4c, 0xcd,
	0x9a, 0x4a, 0xbb, 0x90, 0x92, 0x87, 0xe2, 0xf6, 0xd0, 0x5d, 0x9b, 0xcb, 0x64, 0x43, 0xb0, 0xd8,
	0xa2, 0xab, 0xb8, 0x26, 0xda, 0x3f, 0x0c, 0x0f, 0x0d, 0x61, 0xeb, 0x63, 0x5d, 0x62, 0x8c, 0xe4,
	0x36, 0x5c, 0xb4, 0x14, 0x0e, 0x94, 0x6a, 0x09, 0x65, 0x60, 0xa0, 0x96, 0xb5, 0x9a, 0xac, 0x6f,
	0x6f, 0x93, 0x87, 0x23, 0x27, 0x25, 0xee, 0x7c, 0x75, 0xe4, 0x94, 0x09, 0x9e, 0x90, 0x47, 0xd0,
	0xa3, 0xd1, 0x41, 0x4b, 0x02, 0x40, 0xa0, 0x40, 0x6e, 0xa7, 0xe7, 0xa2, 0x53, 0x0b, 0xfc, 0xb6,
	0x34, 0xc0, 0xa4, 0xaf, 0x32, 0x1d, 0x03, 0xb9, 0x83, 0x9e, 0x89, 0x96, 0x16, 0xe8, 0xf4, 0xc0,
	0x58, 0x05, 0x43, 0xee, 0x0c, 0x56, 0x1f, 0x28, 0xd5, 0x66, 0xba, 0xad, 0xd5, 0x78, 0x8b, 0xa5,
	0xa0, 0xc9, 0x23, 0xeb, 0x6b, 0x14, 0xa8, 0xbf, 0xc6, 0x5d, 0xf4, 0xd6, 0xe8, 0xa6, 0x05, 0x3a,
	0xf6, 0xef, 0x86, 0xda, 0x05, 0x5d, 0x28, 0x9e, 0xa7, 0x27, 0xa2, 0x23, 0x1e, 0x3b, 0xcb, 0x20,
	0x0d, 0xd8, 0x94, 0xe5, 0x92, 0x3c, 0xca, 0x79, 0x19, 0xe0, 0xdf, 0xca, 0x8b, 0xfd, 0xeb, 0x7b,
	0x79, 0xb4, 0xf3, 0xb2, 0xca, 0xe4, 0x1c, 0x5b, 0x8f, 0xb1, 0xb9, 0x90, 0xb3, 0xe5, 0xe3, 0xe4,
	0xb1, 0xf4, 0x6c, 0x74, 0xd2, 0x59, 0x2d, 0xe6, 0xea, 0x71, 0x78, 0xf8, 0xf3, 0x2a, 0x15, 0x55,
	0x8f, 0xf7, 0x57, 0xae, 0x33, 0xf5, 0x84, 0xda, 0x02, 0x0b, 0x88, 0x7a, 0x22, 0xbd, 0x25, 0x3a,
	0x37, 0xaf, 0x32, 0xc7, 0xd3, 0x93, 0x16, 0xeb, 0xcd, 0x31, 0xf1, 0x64, 0xac, 0x43, 0xa7, 0x57,
	0xa3, 0xf3, 0x29, 0x18, 0x6b, 0x33, 0xc1, 0x1c, 0x0c, 0x17, 0xe2, 0x72, 0x48, 0x9e, 0xea, 0x0a,
	0xd8, 0x4a, 0x7a, 0xb0, 0x8d, 0xfd, 0x65, 0xd6, 0xe6, 0xda, 0xa4, 0xe4, 0x69, 0x65, 0x09, 0x70,
	0x39, 0xec, 0x98, 0x4d, 0x99, 0x80, 0x6e, 0x29, 0x69, 0x52, 0x9d, 0xd9, 0x89, 0x42, 0x9e, 0xee,
	0x72, 0x1c, 0x4b, 0xc0, 0xe5, 0x70, 0xd3, 0xd5, 0xc5, 0xaa, 0x62, 0xc9, 0x7a, 0x3a, 0x02, 0xbd,
	0x21, 0xd8, 0x0c, 0xb4, 0xc1, 0xf2, 0x33, 0xe4, 0x02, 0x46, 0x53, 0xb6, 0xbe, 0x9e, 0x52, 0xe3,
	0x81, 0x42, 0x4d, 0x5b, 0xa6, 0x2d, 0x97, 0xe1, 0x9b, 0x52, 0x14, 0x32, 0x33, 0x18, 0x81, 0x06,
	0xb2, 0xec, 0x90, 0x2d, 0xa6, 0x27, 0x1d, 0xe9, 0x21, 0x17, 0xe9, 0xb1, 0xe8, 0x90, 0x5b, 0xaf,
	0x33, 0x1e, 0xab, 0x2b, 0x5c, 0x40, 0xbe, 0x56, 0xdb, 0x85, 0xd2, 0x83, 0xd8, 0xf6, 0xd2, 0x10,
	0xbe, 0xdb, 0x91, 0xeb, 0xe0, 0xb9, 0x1d, 0xe6, 0x7a, 0x2b, 0xd8, 0x56, 0xdd, 0x0a, 0x65, 0xaf,
	0xe9, 0xe4, 0x93, 0xa1, 0xc5, 0xf4, 0x50, 0x0d, 0x54, 0x1e, 0x30, 0x79, 0x06, 0x06, 0x83, 0x6a,
	0x4d, 0x21, 0xd6, 0x54, 0xde, 0x9d, 0x4c, 0x5b, 0x65, 0x32, 0x21, 0xcf, 0x2c, 0x7a, 0xfe, 0xd6,
	0x88, 0x0b, 0x58, 0x8f, 0xe3, 0x6c, 0xc2, 0x21, 0x21, 0xab, 0x2e, 0xfa, 0x66, 0x9a, 0xb2, 0x78,
	0x07, 0x3b, 0xa0, 0xca, 0xd2, 0xe6, 0x78, 0xac, 0x48, 0xd7, 0x25, 0x30, 0xb6, 0xa6, 0xa6, 0x9c,
	0xe1, 0x48, 0xb0, 0xc0, 0x1a, 0x9e, 0xd9, 0xff, 0xe9, 0x4a, 0xeb, 0xe8, 0x0f, 0xcf, 0x73, 0x55,
	0xc5, 0x3b, 0x38, 0x97, 0x31, 0xd6, 0xfc, 0x38, 0x37, 0xb0, 0xa5, 0x87, 0x0d, 0x97, 0xdc, 0x83,
	0x6b, 0x54, 0xb2, 0x8e, 0x9c, 0x82, 0x4c, 0x95, 0x9e, 0x91, 0x9e, 0xf3, 0x93, 0x03, 0x97, 0xb8,
	0x9d, 0x9b, 0xd6, 0xa6, 0x1f, 0xf6, 0xf5, 0x02, 0x2a, 0xcb, 0x6b, 0x80, 0x3d, 0xae, 0x82, 0xb7,
	0x98, 0xd8, 0x61, 0x3e, 0xbe, 0x19, 0x8e, 0x8c, 0x0d, 0xb6, 0x2b, 0x99, 0x73, 0x7d, 0x09, 0xb1,
	0xcb, 0x2a, 0xc3, 0x5d, 0xb7, 0x94, 0x4c, 0xb5, 0x12, 0x25, 0xdf, 0x5b, 0xd8, 0x7f, 0x0a, 0xac,
	0x63, 0x4c, 0x06, 0x2d, 0x35, 0x1e, 0x33, 0x99, 0x98, 0x81, 0x2a, 0x75, 0x9e, 0x15, 0x6e, 0xa7,
	0xaa, 0xd7, 0xcb, 0x38, 0x30, 0x0a, 0xba, 0xcc, 0x0a, 0x30, 0x91, 0x2b, 0x90, 0x67, 0x63, 0x5a,
	0x39, 0x79, 0x0f, 0x26, 0x8c, 0xeb, 0x02, 0x79, 0x4e, 0x7e, 0x43, 0xe8, 0xa4, 0x30, 0x36, 0x79,
	0x83, 0x26, 0xcf, 0x75, 0x39, 0xe8, 0x1d, 0x88, 0xc5, 0xc9, 0xf3, 0x70, 0xbc, 0x38, 0xc4, 0x76,
	0xfa, 0xe7, 0xa3, 0x6e, 0xee, 0x6a, 0x85, 0x99, 0x35, 0x55, 0x31, 0xfb, 0x02, 0x97, 0x4d, 0xe8,
	0x73, 0x30, 0xe2, 0x06, 0x5d, 0x90, 0x17, 0x3a, 0x29, 0x0e, 0xa7, 0x52, 0xca, 0x9c, 0x14, 0x59,
	0x42, 0xa9, 0xdd, 0xe5, 0x15, 0x94, 0x56, 0xbb, 0x6c, 0x31, 0x83, 0x5d, 0x27, 0x76, 0xba, 0x81,
	0x34, 0xc1, 0x2c, 0xad, 0x74, 0xd7, 0x33, 0x14, 0x82, 0xab, 0x5b, 0x5f, 0xb8, 0x1d, 0x9e, 0xcb,
	0x65, 0x95, 0xe9, 0xf5, 0xdd, 0xa2, 0x02, 0x86, 0xae, 0xbd, 0x2c, 0xc0, 0x46, 0x58, 0xd0, 0x95,
	0x5d, 0x5b, 0x73, 0x90, 0x89, 0x98, 0xe5, 0x20, 0x77, 0x7d, 0x72, 0x11, 0xf8, 0xa2, 0x70, 0xc5,
	0x35, 0xc8, 0x52, 0xcd, 0x44, 0x8e, 0xed, 0x84, 0x2b, 0x06, 0x98, 0x40, 0x6e, 0x2b, 0xbb, 0x8b,
	0x12, 0xc6, 0x85, 0xc7, 0xb1, 0x3b, 0xa1, 0x39, 0x44, 0x62, 0x02, 0x54, 0x36, 0x4d, 0xae, 0x73,
	0xb9, 0x0a, 0x6f, 0x12, 0xa5, 0x7c, 0x12, 0xe6, 0xff, 0xdd, 0x1a, 0x6b, 0x38, 0x87, 0xee, 0x75,
	0x25, 0x3b, 0x0f, 0xe9, 0x30, 0xb2, 0xbe, 0xed, 0x23, 0x99, 0x06, 0x43, 0x4c, 0x18, 0x99, 0x87,
	0xa4, 0xa1, 0xcd, 0x2a, 0x1f, 0x8e, 0xd2, 0xdc, 0x5b, 0x16, 0xda, 0x78, 0xc8, 0x34, 0x64, 0xae,
	0xa9, 0xc7, 0x4a, 0x43, 0x11, 0xc3, 0x6e, 0xc8, 0x5c, 0x80, 0xdd, 0x17, 0x96, 0xee, 0x05, 0xae,
	0x84, 0x1a, 0xf2, 0xd8, 0x11, 0x3b, 0x73, 0xfd, 0x72, 0x31, 0x7c, 0x35, 0xe4, 0x64, 0x05, 0xb4,
	0xe2, 0x71, 0x0e, 0xbd, 0x38, 0xe4, 0xc4, 0x87, 0x5e, 0x12, 0xc6, 0xda, 0x53, 0x57, 0x54, 0xea,
	0xb0, 0x97, 0x86, 0xb1, 0x06, 0xd8, 0xcb, 0xc2, 0x58, 0xbb, 0xd8, 0xa3, 0x65, 0x15, 0xcc, 0xcb,
	0xe9, 0x29, 0x3f, 0xd6, 0x3a, 0xfc, 0x8a, 0x06, 0x3d, 0x11, 0xb4, 0x19, 0xc3, 0x95, 0x74, 0xae,
	0x5f, 0x69, 0xc1, 0xca, 0x38, 0x00, 0x5f, 0x55, 0xb3, 0xec, 0x32, 0x63, 0xf8, 0xb4, 0x18, 0x19,
	0xaf, 0xae, 0x59, 0x06, 0xe0, 0x6b, 0x1a, 0xf4, 0x70, 0xb4, 0xdf, 0xb3, 0xe4, 0xc6, 0x70, 0x01,
	0xe4, 0xb5, 0x56, 0xee, 0x19, 0x15, 0xf2, 0xd7, 0x35, 0xe8, 0x71, 0x9f, 0xd0, 0x2d, 0xa5, 0x77,
	0xa0, 0xc8, 0xbf, 0xd7, 0x5b, 0xac, 0xb2, 0xf1, 0xb1, 0x37, 0x34, 0xe8, 0xd9, 0x68, 0x29, 0x28,
	0x00, 0x3d, 0x9c, 0xb5, 0xd8, 0xc4, 0xf5, 0x51, 0x43, 0xde, 0x68, 0x55, 0x82, 0x4a, 0xa8, 0xab,
	0xbc, 0xa9, 0xe6, 0x25, 0xbf, 0x97, 0x07, 0x2a, 0x6f, 0xae, 0x79, 0x59, 0xa0, 0xf2, 0x96, 0x06,
	0x3d, 0xe4, 0x37, 0xa3, 0xb6, 0xc0, 0x51, 0x4f, 0xde, 0x6a, 0xc5, 0x5e, 0xe1, 0xe7, 0xe2, 0xb7,
	0xd5, 0x76, 0x7c, 0x21, 0xd3, 0xdc, 0xe5, 0xe6, 0xdb, 0x6b, 0x3b, 0xf6, 0xb1, 0x77, 0xd4, 0xce,
	0xa4, 0x25, 0x14, 0xdb, 0x71, 0xe0, 0x3b, 0x6b, 0x67, 0x12, 0x80, 0xef, 0x6a, 0xd0, 0x73, 0xd1,
	0xc9, 0x70, 0xea, 0x99, 0x8e, 0x6c, 0xf6, 0x53, 0x66, 0xb8, 0x69, 0xe3, 0x7e, 0xc8, 0xbb, 0xad,
	0x4e, 0xe5, 0x60, 0x91, 0xce, 0x7b, 0x1a, 0xf4, 0xe6, 0xe8, 0x8c, 0xef, 0x67, 0xe1, 0x55, 0xe1,
	0xbd, 0x56, 0xcd, 0x77, 0xb5, 0x50, 0xed, 0x7d, 0x0d, 0x7a, 0xd4, 0x1f, 0x54, 0xcb, 0x50, 0x5c,
	0x76, 0xc8, 0xfb, 0x2d, 0x52, 0x39, 0xa8, 0x90, 0x0f, 0x34, 0xe8, 0x49, 0xff, 0xc1, 0xd4, 0x83,
	0x29, 0x9f, 0x56, 0x07, 0xf1, 0x41, 0x0b, 0x7b, 0xb5, 0x14, 0xc2, 0x1f, 0xaa, 0x31, 0xbf, 0xc2,
	0x93, 0x04, 0x8a, 0x68, 0x3e, 0x5c, 0x63, 0xde, 0xc7, 0x3e, 0x52, 0x72, 0xe3, 0x2e, 0x49, 0xf3,
	0x57, 0xba, 0x8f, 0xd6, 0x22, 0x5b, 0x61, 0x42, 0x64, 0x31, 0x97, 0x76, 0xde, 0x1b, 0xf2, 0xb1,
	0x5a, 0x64, 0x35, 0xf8, 0xe3, 0x0d, 0x7a, 0x26, 0x3a, 0x11, 0xdc, 0x41, 0x32, 0x81, 0x8f, 0xdc,
	0x32, 0xf6, 0x4f, 0x58, 0x8d, 0xca, 0xc1, 0xbc, 0xc6, 0x27, 0x1b, 0x74, 0xc9, 0x1f, 0x42, 0xcb,
	0x90, 0x42, 0x9c, 0xba, 0x1c, 0xf8, 0x94, 0x45, 0x7d, 0x4e, 0x7d, 0xf4, 0xd3, 0xb5, 0xf0, 0x6a,
	0x0f, 0xd1, 0xcf, 0x34, 0xc2, 0x46, 0x53, 0x7f, 0xc6, 0x7e, 0xb6, 0x56, 0x46, 0x9b, 0x32, 0xce,
	0xef, 0x25, 0x55, 0x74, 0x9f, 0xab, 0x95, 0xd1, 0x02, 0x95, 0xcf, 0xd7, 0xbc, 0x6c, 0x68, 0xc0,
	0xfb, 0xc2, 0x32, 0x6c, 0x03, 0x2b, 0x7a, 0xfe, 0xfd, 0x35, 0x2f, 0x0b, 0x54, 0xbe, 0xb0, 0xd8,
	0x4b, 0x0f, 0xa6, 0xe0, 0xfa, 0xe2, 0x17, 0x17, 0x7b, 0xf1, 0x55, 0xbe, 0x54, 0x6f, 0x9d, 0x7e,
	0x8f, 0xfb, 0x72, 0xbd, 0x75, 0xfa, 0xe0, 0x57, 0x6a, 0x96, 0xfd, 0x34, 0x93, 0xd2, 0xf1, 0xfc,
	0xd5, 0x9a, 0x65, 0x00, 0x7e, 0xad, 0x76, 0x80, 0xfd, 0x6c, 0x3c, 0x56, 0x25, 0xfa, 0xf5, 0xda,
	0x01, 0x86, 0xe8, 0x37, 0x1a, 0xf4, 0xa0, 0x7f, 0xc7, 0xd9, 0x34, 0xa0, 0xef, 0x22, 0xdf, 0xb4,
	0x52, 0x8f, 0x74, 0x2b, 0xfd, 0x56, 0x83, 0x9e, 0xf6, 0x6f, 0xa7, 0x9b, 0xd2, 0xa4, 0x6a, 0xe2,
	0xf5, 0xb3, 0x6f, 0x5b, 0x05, 0xff, 0xac, 0x6a, 0x0a, 0xdf, 0x99, 0x2b, 0x43, 0xc3, 0x4d, 0x6a,
	0x9f, 0x2c, 0x08, 0x7f, 0x77, 0xae, 0x0c, 0x03, 0xf8, 0x7b, 0x0d, 0x7a, 0xcc, 0x9f, 0xf6, 0xcb,
	0xec, 0xaa, 0xdb, 0xc6, 0xf7, 0x2d, 0xe4, 0x65, 0x69, 0x05, 0xfd, 0xa0, 0x41, 0xf7, 0xe7, 0xf7,
	0x4b, 0x77, 0xab, 0x27, 0x3f, 0x2c, 0xb7, 0xd7, 0xe5, 0x32, 0x29, 0xee, 0xca, 0xe4, 0x47, 0x73,
	0x75, 0x50, 0x34, 0x9e, 0x2b, 0x02, 0x0c, 0xf9, 0xf1, 0x5c, 0x1d, 0xf8, 0xe8, 0x4f, 0x6a, 0x34,
	0xe6, 0x37, 0xdb, 0x9f, 0xd6, 0x68, 0xcc, 0xa5, 0x3f, 0xb3, 0x5d, 0x0a, 0x1f, 0x3f, 0xc2, 0x7e,
	0xfc, 0x6b, 0x4e, 0x19, 0x17, 0xc8, 0x11, 0xf9, 0xb9, 0x6d, 0xfc, 0x5b, 0x6c, 0x36, 0x51, 0x5c,
	0xa6, 0xab, 0xdc, 0xa4, 0xf6, 0xab, 0xdf, 0x2f, 0x1a, 0xf4, 0x80, 0xff, 0xf8, 0xe8, 0xb1, 0x18,
	0xc8, 0x2f, 0xad, 0xd0, 0xe3, 0x0a, 0x85, 0xbf, 0xaa, 0xe7, 0x10, 0x1f, 0x73, 0xc1, 0x8a, 0xc9,
	0xf7, 0xeb, 0x7a, 0x0e, 0xf9, 0xe0, 0x6f, 0xca, 0x36, 0x86, 0xcf, 0xd1, 0xe2, 0x93, 0x61, 0xfe,
	0x02, 0x23, 0xbf, 0xb5, 0xe4, 0x36, 0x85, 0x06, 0x96, 0xcc, 0xfa, 0x13, 0xb6, 0x2b, 0xb9, 0x1c,
	0xae, 0x32, 0x3d, 0x65, 0xe4, 0x77, 0xf5, 0x51, 0x79, 0xdf, 0x88, 0x65, 0x26, 0x85, 0xa4, 0x7a,
	0x3d, 0xfc, 0xbe, 0x0c, 0x74, 0xd3, 0x40, 0x97, 0x4b, 0x3e, 0x66, 0x13, 0xf2, 0x87, 0x72, 0xc4,
	0x6d, 0x1a, 0xe8, 0xc8, 0x6d, 0xb5, 0xc1, 0x24, 0x08, 0xf2, 0x47, 0x2b, 0xb6, 0xdf, 0x4a, 0xfd,
	0xcf, 0x9e, 0x7f, 0x2a, 0xb9, 0x5f, 0x61, 0x7a, 0x0a, 0xc6, 0x7e, 0xb3, 0x72, 0x2b, 0x90, 0x3f,
	0xdb, 0xd0, 0x0b, 0x04, 0x34, 0x3e, 0xe6, 0x8a, 0x47, 0x49, 0x42, 0xfe, 0x62, 0x4f, 0xa0, 0x08,
	0x3d, 0x0f, 0x11, 0x12, 0xf2, 0xd7, 0xb2, 0x2d, 0x15, 0x0f, 0x47, 0x60, 0x13, 0x25, 0xcd, 0x32,
	0x37, 0x78, 0x0c, 0x09, 0xf9, 0x5b, 0x83, 0x1e, 0x89, 0x68, 0xf1, 0x29, 0xac, 0x07, 0x2c, 0x2e,
	0xa8, 0x20, 0x7f, 0xb7, 0x40, 0x71, 0x98, 0x66, 0x3d, 0x4b, 0xd7, 0xb7, 0x7b, 0x4c, 0x0e, 0x81,
	0xfc, 0xc3, 0x06, 0xee, 0x00, 0xf7, 0xd1, 0x83, 0xfc, 0x33, 0x10, 0x5b, 0xfd, 0xa6, 0x8e, 0xc9,
	0xbf, 0xca, 0x3c, 0x47, 0xb2, 0x07, 0x20, 0x60, 0xa2, 0x74, 0xf5, 0xf5, 0xeb, 0xdf, 0xd6, 0xaa,
	0xf8, 0x14, 0x83, 0x39, 0xd3, 0x12, 0xcc, 0x18, 0xf2, 0x9f, 0x72, 0xba, 0xa1, 0x55, 0x8b, 0xc9,
	0x18, 0x44, 0xfe, 0x59, 0xf9, 0xbf, 0x8d, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xcc, 0xe5,
	0x32, 0xd9, 0x16, 0x00, 0x00,
}
