// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s2clientprotocol/raw.proto

package SC2APIProtocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DisplayType int32

const (
	DisplayType_Visible  DisplayType = 1
	DisplayType_Snapshot DisplayType = 2
	DisplayType_Hidden   DisplayType = 3
)

var DisplayType_name = map[int32]string{
	1: "Visible",
	2: "Snapshot",
	3: "Hidden",
}
var DisplayType_value = map[string]int32{
	"Visible":  1,
	"Snapshot": 2,
	"Hidden":   3,
}

func (x DisplayType) Enum() *DisplayType {
	p := new(DisplayType)
	*p = x
	return p
}
func (x DisplayType) String() string {
	return proto.EnumName(DisplayType_name, int32(x))
}
func (x *DisplayType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DisplayType_value, data, "DisplayType")
	if err != nil {
		return err
	}
	*x = DisplayType(value)
	return nil
}
func (DisplayType) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type Alliance int32

const (
	Alliance_Self    Alliance = 1
	Alliance_Ally    Alliance = 2
	Alliance_Neutral Alliance = 3
	Alliance_Enemy   Alliance = 4
)

var Alliance_name = map[int32]string{
	1: "Self",
	2: "Ally",
	3: "Neutral",
	4: "Enemy",
}
var Alliance_value = map[string]int32{
	"Self":    1,
	"Ally":    2,
	"Neutral": 3,
	"Enemy":   4,
}

func (x Alliance) Enum() *Alliance {
	p := new(Alliance)
	*p = x
	return p
}
func (x Alliance) String() string {
	return proto.EnumName(Alliance_name, int32(x))
}
func (x *Alliance) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Alliance_value, data, "Alliance")
	if err != nil {
		return err
	}
	*x = Alliance(value)
	return nil
}
func (Alliance) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

type CloakState int32

const (
	CloakState_Cloaked         CloakState = 1
	CloakState_CloakedDetected CloakState = 2
	CloakState_NotCloaked      CloakState = 3
)

var CloakState_name = map[int32]string{
	1: "Cloaked",
	2: "CloakedDetected",
	3: "NotCloaked",
}
var CloakState_value = map[string]int32{
	"Cloaked":         1,
	"CloakedDetected": 2,
	"NotCloaked":      3,
}

func (x CloakState) Enum() *CloakState {
	p := new(CloakState)
	*p = x
	return p
}
func (x CloakState) String() string {
	return proto.EnumName(CloakState_name, int32(x))
}
func (x *CloakState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CloakState_value, data, "CloakState")
	if err != nil {
		return err
	}
	*x = CloakState(value)
	return nil
}
func (CloakState) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

type StartRaw struct {
	MapSize          *Size2DI    `protobuf:"bytes,1,opt,name=map_size,json=mapSize" json:"map_size,omitempty"`
	PathingGrid      *ImageData  `protobuf:"bytes,2,opt,name=pathing_grid,json=pathingGrid" json:"pathing_grid,omitempty"`
	TerrainHeight    *ImageData  `protobuf:"bytes,3,opt,name=terrain_height,json=terrainHeight" json:"terrain_height,omitempty"`
	PlacementGrid    *ImageData  `protobuf:"bytes,4,opt,name=placement_grid,json=placementGrid" json:"placement_grid,omitempty"`
	PlayableArea     *RectangleI `protobuf:"bytes,5,opt,name=playable_area,json=playableArea" json:"playable_area,omitempty"`
	StartLocations   []*Point2D  `protobuf:"bytes,6,rep,name=start_locations,json=startLocations" json:"start_locations,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *StartRaw) Reset()                    { *m = StartRaw{} }
func (m *StartRaw) String() string            { return proto.CompactTextString(m) }
func (*StartRaw) ProtoMessage()               {}
func (*StartRaw) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *StartRaw) GetMapSize() *Size2DI {
	if m != nil {
		return m.MapSize
	}
	return nil
}

func (m *StartRaw) GetPathingGrid() *ImageData {
	if m != nil {
		return m.PathingGrid
	}
	return nil
}

func (m *StartRaw) GetTerrainHeight() *ImageData {
	if m != nil {
		return m.TerrainHeight
	}
	return nil
}

func (m *StartRaw) GetPlacementGrid() *ImageData {
	if m != nil {
		return m.PlacementGrid
	}
	return nil
}

func (m *StartRaw) GetPlayableArea() *RectangleI {
	if m != nil {
		return m.PlayableArea
	}
	return nil
}

func (m *StartRaw) GetStartLocations() []*Point2D {
	if m != nil {
		return m.StartLocations
	}
	return nil
}

type ObservationRaw struct {
	Player           *PlayerRaw `protobuf:"bytes,1,opt,name=player" json:"player,omitempty"`
	Units            []*Unit    `protobuf:"bytes,2,rep,name=units" json:"units,omitempty"`
	MapState         *MapState  `protobuf:"bytes,3,opt,name=map_state,json=mapState" json:"map_state,omitempty"`
	Event            *Event     `protobuf:"bytes,4,opt,name=event" json:"event,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ObservationRaw) Reset()                    { *m = ObservationRaw{} }
func (m *ObservationRaw) String() string            { return proto.CompactTextString(m) }
func (*ObservationRaw) ProtoMessage()               {}
func (*ObservationRaw) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *ObservationRaw) GetPlayer() *PlayerRaw {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *ObservationRaw) GetUnits() []*Unit {
	if m != nil {
		return m.Units
	}
	return nil
}

func (m *ObservationRaw) GetMapState() *MapState {
	if m != nil {
		return m.MapState
	}
	return nil
}

func (m *ObservationRaw) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type PowerSource struct {
	Pos              *Point   `protobuf:"bytes,1,opt,name=pos" json:"pos,omitempty"`
	Radius           *float32 `protobuf:"fixed32,2,opt,name=radius" json:"radius,omitempty"`
	Tag              *uint64  `protobuf:"varint,3,opt,name=tag" json:"tag,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PowerSource) Reset()                    { *m = PowerSource{} }
func (m *PowerSource) String() string            { return proto.CompactTextString(m) }
func (*PowerSource) ProtoMessage()               {}
func (*PowerSource) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *PowerSource) GetPos() *Point {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *PowerSource) GetRadius() float32 {
	if m != nil && m.Radius != nil {
		return *m.Radius
	}
	return 0
}

func (m *PowerSource) GetTag() uint64 {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return 0
}

type PlayerRaw struct {
	PowerSources     []*PowerSource `protobuf:"bytes,1,rep,name=power_sources,json=powerSources" json:"power_sources,omitempty"`
	Camera           *Point         `protobuf:"bytes,2,opt,name=camera" json:"camera,omitempty"`
	UpgradeIds       []uint32       `protobuf:"varint,3,rep,name=upgrade_ids,json=upgradeIds" json:"upgrade_ids,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PlayerRaw) Reset()                    { *m = PlayerRaw{} }
func (m *PlayerRaw) String() string            { return proto.CompactTextString(m) }
func (*PlayerRaw) ProtoMessage()               {}
func (*PlayerRaw) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *PlayerRaw) GetPowerSources() []*PowerSource {
	if m != nil {
		return m.PowerSources
	}
	return nil
}

func (m *PlayerRaw) GetCamera() *Point {
	if m != nil {
		return m.Camera
	}
	return nil
}

func (m *PlayerRaw) GetUpgradeIds() []uint32 {
	if m != nil {
		return m.UpgradeIds
	}
	return nil
}

type UnitOrder struct {
	AbilityId *uint32 `protobuf:"varint,1,opt,name=ability_id,json=abilityId" json:"ability_id,omitempty"`
	// Types that are valid to be assigned to Target:
	//	*UnitOrder_TargetWorldSpacePos
	//	*UnitOrder_TargetUnitTag
	Target           isUnitOrder_Target `protobuf_oneof:"target"`
	Progress         *float32           `protobuf:"fixed32,4,opt,name=progress" json:"progress,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *UnitOrder) Reset()                    { *m = UnitOrder{} }
func (m *UnitOrder) String() string            { return proto.CompactTextString(m) }
func (*UnitOrder) ProtoMessage()               {}
func (*UnitOrder) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

type isUnitOrder_Target interface {
	isUnitOrder_Target()
}

type UnitOrder_TargetWorldSpacePos struct {
	TargetWorldSpacePos *Point `protobuf:"bytes,2,opt,name=target_world_space_pos,json=targetWorldSpacePos,oneof"`
}
type UnitOrder_TargetUnitTag struct {
	TargetUnitTag uint64 `protobuf:"varint,3,opt,name=target_unit_tag,json=targetUnitTag,oneof"`
}

func (*UnitOrder_TargetWorldSpacePos) isUnitOrder_Target() {}
func (*UnitOrder_TargetUnitTag) isUnitOrder_Target()       {}

func (m *UnitOrder) GetTarget() isUnitOrder_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *UnitOrder) GetAbilityId() uint32 {
	if m != nil && m.AbilityId != nil {
		return *m.AbilityId
	}
	return 0
}

func (m *UnitOrder) GetTargetWorldSpacePos() *Point {
	if x, ok := m.GetTarget().(*UnitOrder_TargetWorldSpacePos); ok {
		return x.TargetWorldSpacePos
	}
	return nil
}

func (m *UnitOrder) GetTargetUnitTag() uint64 {
	if x, ok := m.GetTarget().(*UnitOrder_TargetUnitTag); ok {
		return x.TargetUnitTag
	}
	return 0
}

func (m *UnitOrder) GetProgress() float32 {
	if m != nil && m.Progress != nil {
		return *m.Progress
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UnitOrder) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UnitOrder_OneofMarshaler, _UnitOrder_OneofUnmarshaler, _UnitOrder_OneofSizer, []interface{}{
		(*UnitOrder_TargetWorldSpacePos)(nil),
		(*UnitOrder_TargetUnitTag)(nil),
	}
}

func _UnitOrder_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UnitOrder)
	// target
	switch x := m.Target.(type) {
	case *UnitOrder_TargetWorldSpacePos:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TargetWorldSpacePos); err != nil {
			return err
		}
	case *UnitOrder_TargetUnitTag:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.TargetUnitTag))
	case nil:
	default:
		return fmt.Errorf("UnitOrder.Target has unexpected type %T", x)
	}
	return nil
}

func _UnitOrder_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UnitOrder)
	switch tag {
	case 2: // target.target_world_space_pos
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Point)
		err := b.DecodeMessage(msg)
		m.Target = &UnitOrder_TargetWorldSpacePos{msg}
		return true, err
	case 3: // target.target_unit_tag
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Target = &UnitOrder_TargetUnitTag{x}
		return true, err
	default:
		return false, nil
	}
}

func _UnitOrder_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UnitOrder)
	// target
	switch x := m.Target.(type) {
	case *UnitOrder_TargetWorldSpacePos:
		s := proto.Size(x.TargetWorldSpacePos)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UnitOrder_TargetUnitTag:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.TargetUnitTag))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PassengerUnit struct {
	Tag              *uint64  `protobuf:"varint,1,opt,name=tag" json:"tag,omitempty"`
	Health           *float32 `protobuf:"fixed32,2,opt,name=health" json:"health,omitempty"`
	HealthMax        *float32 `protobuf:"fixed32,3,opt,name=health_max,json=healthMax" json:"health_max,omitempty"`
	Shield           *float32 `protobuf:"fixed32,4,opt,name=shield" json:"shield,omitempty"`
	Energy           *float32 `protobuf:"fixed32,5,opt,name=energy" json:"energy,omitempty"`
	UnitType         *uint32  `protobuf:"varint,6,opt,name=unit_type,json=unitType" json:"unit_type,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PassengerUnit) Reset()                    { *m = PassengerUnit{} }
func (m *PassengerUnit) String() string            { return proto.CompactTextString(m) }
func (*PassengerUnit) ProtoMessage()               {}
func (*PassengerUnit) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *PassengerUnit) GetTag() uint64 {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return 0
}

func (m *PassengerUnit) GetHealth() float32 {
	if m != nil && m.Health != nil {
		return *m.Health
	}
	return 0
}

func (m *PassengerUnit) GetHealthMax() float32 {
	if m != nil && m.HealthMax != nil {
		return *m.HealthMax
	}
	return 0
}

func (m *PassengerUnit) GetShield() float32 {
	if m != nil && m.Shield != nil {
		return *m.Shield
	}
	return 0
}

func (m *PassengerUnit) GetEnergy() float32 {
	if m != nil && m.Energy != nil {
		return *m.Energy
	}
	return 0
}

func (m *PassengerUnit) GetUnitType() uint32 {
	if m != nil && m.UnitType != nil {
		return *m.UnitType
	}
	return 0
}

type Unit struct {
	// Fields are populated based on type/alliance
	DisplayType   *DisplayType `protobuf:"varint,1,opt,name=display_type,json=displayType,enum=SC2APIProtocol.DisplayType" json:"display_type,omitempty"`
	Alliance      *Alliance    `protobuf:"varint,2,opt,name=alliance,enum=SC2APIProtocol.Alliance" json:"alliance,omitempty"`
	Tag           *uint64      `protobuf:"varint,3,opt,name=tag" json:"tag,omitempty"`
	UnitType      *uint32      `protobuf:"varint,4,opt,name=unit_type,json=unitType" json:"unit_type,omitempty"`
	Owner         *int32       `protobuf:"varint,5,opt,name=owner" json:"owner,omitempty"`
	Pos           *Point       `protobuf:"bytes,6,opt,name=pos" json:"pos,omitempty"`
	Facing        *float32     `protobuf:"fixed32,7,opt,name=facing" json:"facing,omitempty"`
	Radius        *float32     `protobuf:"fixed32,8,opt,name=radius" json:"radius,omitempty"`
	BuildProgress *float32     `protobuf:"fixed32,9,opt,name=build_progress,json=buildProgress" json:"build_progress,omitempty"`
	Cloak         *CloakState  `protobuf:"varint,10,opt,name=cloak,enum=SC2APIProtocol.CloakState" json:"cloak,omitempty"`
	DetectRange   *float32     `protobuf:"fixed32,31,opt,name=detect_range,json=detectRange" json:"detect_range,omitempty"`
	RadarRange    *float32     `protobuf:"fixed32,32,opt,name=radar_range,json=radarRange" json:"radar_range,omitempty"`
	IsSelected    *bool        `protobuf:"varint,11,opt,name=is_selected,json=isSelected" json:"is_selected,omitempty"`
	IsOnScreen    *bool        `protobuf:"varint,12,opt,name=is_on_screen,json=isOnScreen" json:"is_on_screen,omitempty"`
	IsBlip        *bool        `protobuf:"varint,13,opt,name=is_blip,json=isBlip" json:"is_blip,omitempty"`
	IsPowered     *bool        `protobuf:"varint,35,opt,name=is_powered,json=isPowered" json:"is_powered,omitempty"`
	// Not populated for snapshots
	Health          *float32 `protobuf:"fixed32,14,opt,name=health" json:"health,omitempty"`
	HealthMax       *float32 `protobuf:"fixed32,15,opt,name=health_max,json=healthMax" json:"health_max,omitempty"`
	Shield          *float32 `protobuf:"fixed32,16,opt,name=shield" json:"shield,omitempty"`
	Energy          *float32 `protobuf:"fixed32,17,opt,name=energy" json:"energy,omitempty"`
	MineralContents *int32   `protobuf:"varint,18,opt,name=mineral_contents,json=mineralContents" json:"mineral_contents,omitempty"`
	VespeneContents *int32   `protobuf:"varint,19,opt,name=vespene_contents,json=vespeneContents" json:"vespene_contents,omitempty"`
	IsFlying        *bool    `protobuf:"varint,20,opt,name=is_flying,json=isFlying" json:"is_flying,omitempty"`
	IsBurrowed      *bool    `protobuf:"varint,21,opt,name=is_burrowed,json=isBurrowed" json:"is_burrowed,omitempty"`
	// Not populated for enemies
	Orders             []*UnitOrder     `protobuf:"bytes,22,rep,name=orders" json:"orders,omitempty"`
	AddOnTag           *uint64          `protobuf:"varint,23,opt,name=add_on_tag,json=addOnTag" json:"add_on_tag,omitempty"`
	Passengers         []*PassengerUnit `protobuf:"bytes,24,rep,name=passengers" json:"passengers,omitempty"`
	CargoSpaceTaken    *int32           `protobuf:"varint,25,opt,name=cargo_space_taken,json=cargoSpaceTaken" json:"cargo_space_taken,omitempty"`
	CargoSpaceMax      *int32           `protobuf:"varint,26,opt,name=cargo_space_max,json=cargoSpaceMax" json:"cargo_space_max,omitempty"`
	BuffIds            []uint32         `protobuf:"varint,27,rep,name=buff_ids,json=buffIds" json:"buff_ids,omitempty"`
	AssignedHarvesters *int32           `protobuf:"varint,28,opt,name=assigned_harvesters,json=assignedHarvesters" json:"assigned_harvesters,omitempty"`
	IdealHarvesters    *int32           `protobuf:"varint,29,opt,name=ideal_harvesters,json=idealHarvesters" json:"ideal_harvesters,omitempty"`
	WeaponCooldown     *float32         `protobuf:"fixed32,30,opt,name=weapon_cooldown,json=weaponCooldown" json:"weapon_cooldown,omitempty"`
	EngagedTargetTag   *uint64          `protobuf:"varint,34,opt,name=engaged_target_tag,json=engagedTargetTag" json:"engaged_target_tag,omitempty"`
	XXX_unrecognized   []byte           `json:"-"`
}

func (m *Unit) Reset()                    { *m = Unit{} }
func (m *Unit) String() string            { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()               {}
func (*Unit) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *Unit) GetDisplayType() DisplayType {
	if m != nil && m.DisplayType != nil {
		return *m.DisplayType
	}
	return DisplayType_Visible
}

func (m *Unit) GetAlliance() Alliance {
	if m != nil && m.Alliance != nil {
		return *m.Alliance
	}
	return Alliance_Self
}

func (m *Unit) GetTag() uint64 {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return 0
}

func (m *Unit) GetUnitType() uint32 {
	if m != nil && m.UnitType != nil {
		return *m.UnitType
	}
	return 0
}

func (m *Unit) GetOwner() int32 {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return 0
}

func (m *Unit) GetPos() *Point {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *Unit) GetFacing() float32 {
	if m != nil && m.Facing != nil {
		return *m.Facing
	}
	return 0
}

func (m *Unit) GetRadius() float32 {
	if m != nil && m.Radius != nil {
		return *m.Radius
	}
	return 0
}

func (m *Unit) GetBuildProgress() float32 {
	if m != nil && m.BuildProgress != nil {
		return *m.BuildProgress
	}
	return 0
}

func (m *Unit) GetCloak() CloakState {
	if m != nil && m.Cloak != nil {
		return *m.Cloak
	}
	return CloakState_Cloaked
}

func (m *Unit) GetDetectRange() float32 {
	if m != nil && m.DetectRange != nil {
		return *m.DetectRange
	}
	return 0
}

func (m *Unit) GetRadarRange() float32 {
	if m != nil && m.RadarRange != nil {
		return *m.RadarRange
	}
	return 0
}

func (m *Unit) GetIsSelected() bool {
	if m != nil && m.IsSelected != nil {
		return *m.IsSelected
	}
	return false
}

func (m *Unit) GetIsOnScreen() bool {
	if m != nil && m.IsOnScreen != nil {
		return *m.IsOnScreen
	}
	return false
}

func (m *Unit) GetIsBlip() bool {
	if m != nil && m.IsBlip != nil {
		return *m.IsBlip
	}
	return false
}

func (m *Unit) GetIsPowered() bool {
	if m != nil && m.IsPowered != nil {
		return *m.IsPowered
	}
	return false
}

func (m *Unit) GetHealth() float32 {
	if m != nil && m.Health != nil {
		return *m.Health
	}
	return 0
}

func (m *Unit) GetHealthMax() float32 {
	if m != nil && m.HealthMax != nil {
		return *m.HealthMax
	}
	return 0
}

func (m *Unit) GetShield() float32 {
	if m != nil && m.Shield != nil {
		return *m.Shield
	}
	return 0
}

func (m *Unit) GetEnergy() float32 {
	if m != nil && m.Energy != nil {
		return *m.Energy
	}
	return 0
}

func (m *Unit) GetMineralContents() int32 {
	if m != nil && m.MineralContents != nil {
		return *m.MineralContents
	}
	return 0
}

func (m *Unit) GetVespeneContents() int32 {
	if m != nil && m.VespeneContents != nil {
		return *m.VespeneContents
	}
	return 0
}

func (m *Unit) GetIsFlying() bool {
	if m != nil && m.IsFlying != nil {
		return *m.IsFlying
	}
	return false
}

func (m *Unit) GetIsBurrowed() bool {
	if m != nil && m.IsBurrowed != nil {
		return *m.IsBurrowed
	}
	return false
}

func (m *Unit) GetOrders() []*UnitOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *Unit) GetAddOnTag() uint64 {
	if m != nil && m.AddOnTag != nil {
		return *m.AddOnTag
	}
	return 0
}

func (m *Unit) GetPassengers() []*PassengerUnit {
	if m != nil {
		return m.Passengers
	}
	return nil
}

func (m *Unit) GetCargoSpaceTaken() int32 {
	if m != nil && m.CargoSpaceTaken != nil {
		return *m.CargoSpaceTaken
	}
	return 0
}

func (m *Unit) GetCargoSpaceMax() int32 {
	if m != nil && m.CargoSpaceMax != nil {
		return *m.CargoSpaceMax
	}
	return 0
}

func (m *Unit) GetBuffIds() []uint32 {
	if m != nil {
		return m.BuffIds
	}
	return nil
}

func (m *Unit) GetAssignedHarvesters() int32 {
	if m != nil && m.AssignedHarvesters != nil {
		return *m.AssignedHarvesters
	}
	return 0
}

func (m *Unit) GetIdealHarvesters() int32 {
	if m != nil && m.IdealHarvesters != nil {
		return *m.IdealHarvesters
	}
	return 0
}

func (m *Unit) GetWeaponCooldown() float32 {
	if m != nil && m.WeaponCooldown != nil {
		return *m.WeaponCooldown
	}
	return 0
}

func (m *Unit) GetEngagedTargetTag() uint64 {
	if m != nil && m.EngagedTargetTag != nil {
		return *m.EngagedTargetTag
	}
	return 0
}

type MapState struct {
	Visibility       *ImageData `protobuf:"bytes,1,opt,name=visibility" json:"visibility,omitempty"`
	Creep            *ImageData `protobuf:"bytes,2,opt,name=creep" json:"creep,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MapState) Reset()                    { *m = MapState{} }
func (m *MapState) String() string            { return proto.CompactTextString(m) }
func (*MapState) ProtoMessage()               {}
func (*MapState) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *MapState) GetVisibility() *ImageData {
	if m != nil {
		return m.Visibility
	}
	return nil
}

func (m *MapState) GetCreep() *ImageData {
	if m != nil {
		return m.Creep
	}
	return nil
}

type ActionRaw struct {
	// Types that are valid to be assigned to Action:
	//	*ActionRaw_UnitCommand
	//	*ActionRaw_CameraMove
	//	*ActionRaw_ToggleAutocast
	Action           isActionRaw_Action `protobuf_oneof:"action"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ActionRaw) Reset()                    { *m = ActionRaw{} }
func (m *ActionRaw) String() string            { return proto.CompactTextString(m) }
func (*ActionRaw) ProtoMessage()               {}
func (*ActionRaw) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

type isActionRaw_Action interface {
	isActionRaw_Action()
}

type ActionRaw_UnitCommand struct {
	UnitCommand *ActionRawUnitCommand `protobuf:"bytes,1,opt,name=unit_command,json=unitCommand,oneof"`
}
type ActionRaw_CameraMove struct {
	CameraMove *ActionRawCameraMove `protobuf:"bytes,2,opt,name=camera_move,json=cameraMove,oneof"`
}
type ActionRaw_ToggleAutocast struct {
	ToggleAutocast *ActionRawToggleAutocast `protobuf:"bytes,3,opt,name=toggle_autocast,json=toggleAutocast,oneof"`
}

func (*ActionRaw_UnitCommand) isActionRaw_Action()    {}
func (*ActionRaw_CameraMove) isActionRaw_Action()     {}
func (*ActionRaw_ToggleAutocast) isActionRaw_Action() {}

func (m *ActionRaw) GetAction() isActionRaw_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *ActionRaw) GetUnitCommand() *ActionRawUnitCommand {
	if x, ok := m.GetAction().(*ActionRaw_UnitCommand); ok {
		return x.UnitCommand
	}
	return nil
}

func (m *ActionRaw) GetCameraMove() *ActionRawCameraMove {
	if x, ok := m.GetAction().(*ActionRaw_CameraMove); ok {
		return x.CameraMove
	}
	return nil
}

func (m *ActionRaw) GetToggleAutocast() *ActionRawToggleAutocast {
	if x, ok := m.GetAction().(*ActionRaw_ToggleAutocast); ok {
		return x.ToggleAutocast
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ActionRaw) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ActionRaw_OneofMarshaler, _ActionRaw_OneofUnmarshaler, _ActionRaw_OneofSizer, []interface{}{
		(*ActionRaw_UnitCommand)(nil),
		(*ActionRaw_CameraMove)(nil),
		(*ActionRaw_ToggleAutocast)(nil),
	}
}

func _ActionRaw_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ActionRaw)
	// action
	switch x := m.Action.(type) {
	case *ActionRaw_UnitCommand:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UnitCommand); err != nil {
			return err
		}
	case *ActionRaw_CameraMove:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CameraMove); err != nil {
			return err
		}
	case *ActionRaw_ToggleAutocast:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ToggleAutocast); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ActionRaw.Action has unexpected type %T", x)
	}
	return nil
}

func _ActionRaw_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ActionRaw)
	switch tag {
	case 1: // action.unit_command
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ActionRawUnitCommand)
		err := b.DecodeMessage(msg)
		m.Action = &ActionRaw_UnitCommand{msg}
		return true, err
	case 2: // action.camera_move
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ActionRawCameraMove)
		err := b.DecodeMessage(msg)
		m.Action = &ActionRaw_CameraMove{msg}
		return true, err
	case 3: // action.toggle_autocast
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ActionRawToggleAutocast)
		err := b.DecodeMessage(msg)
		m.Action = &ActionRaw_ToggleAutocast{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ActionRaw_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ActionRaw)
	// action
	switch x := m.Action.(type) {
	case *ActionRaw_UnitCommand:
		s := proto.Size(x.UnitCommand)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ActionRaw_CameraMove:
		s := proto.Size(x.CameraMove)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ActionRaw_ToggleAutocast:
		s := proto.Size(x.ToggleAutocast)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ActionRawUnitCommand struct {
	AbilityId *int32 `protobuf:"varint,1,opt,name=ability_id,json=abilityId" json:"ability_id,omitempty"`
	// Types that are valid to be assigned to Target:
	//	*ActionRawUnitCommand_TargetWorldSpacePos
	//	*ActionRawUnitCommand_TargetUnitTag
	Target           isActionRawUnitCommand_Target `protobuf_oneof:"target"`
	UnitTags         []uint64                      `protobuf:"varint,4,rep,name=unit_tags,json=unitTags" json:"unit_tags,omitempty"`
	QueueCommand     *bool                         `protobuf:"varint,5,opt,name=queue_command,json=queueCommand" json:"queue_command,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *ActionRawUnitCommand) Reset()                    { *m = ActionRawUnitCommand{} }
func (m *ActionRawUnitCommand) String() string            { return proto.CompactTextString(m) }
func (*ActionRawUnitCommand) ProtoMessage()               {}
func (*ActionRawUnitCommand) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

type isActionRawUnitCommand_Target interface {
	isActionRawUnitCommand_Target()
}

type ActionRawUnitCommand_TargetWorldSpacePos struct {
	TargetWorldSpacePos *Point2D `protobuf:"bytes,2,opt,name=target_world_space_pos,json=targetWorldSpacePos,oneof"`
}
type ActionRawUnitCommand_TargetUnitTag struct {
	TargetUnitTag uint64 `protobuf:"varint,3,opt,name=target_unit_tag,json=targetUnitTag,oneof"`
}

func (*ActionRawUnitCommand_TargetWorldSpacePos) isActionRawUnitCommand_Target() {}
func (*ActionRawUnitCommand_TargetUnitTag) isActionRawUnitCommand_Target()       {}

func (m *ActionRawUnitCommand) GetTarget() isActionRawUnitCommand_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *ActionRawUnitCommand) GetAbilityId() int32 {
	if m != nil && m.AbilityId != nil {
		return *m.AbilityId
	}
	return 0
}

func (m *ActionRawUnitCommand) GetTargetWorldSpacePos() *Point2D {
	if x, ok := m.GetTarget().(*ActionRawUnitCommand_TargetWorldSpacePos); ok {
		return x.TargetWorldSpacePos
	}
	return nil
}

func (m *ActionRawUnitCommand) GetTargetUnitTag() uint64 {
	if x, ok := m.GetTarget().(*ActionRawUnitCommand_TargetUnitTag); ok {
		return x.TargetUnitTag
	}
	return 0
}

func (m *ActionRawUnitCommand) GetUnitTags() []uint64 {
	if m != nil {
		return m.UnitTags
	}
	return nil
}

func (m *ActionRawUnitCommand) GetQueueCommand() bool {
	if m != nil && m.QueueCommand != nil {
		return *m.QueueCommand
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ActionRawUnitCommand) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ActionRawUnitCommand_OneofMarshaler, _ActionRawUnitCommand_OneofUnmarshaler, _ActionRawUnitCommand_OneofSizer, []interface{}{
		(*ActionRawUnitCommand_TargetWorldSpacePos)(nil),
		(*ActionRawUnitCommand_TargetUnitTag)(nil),
	}
}

func _ActionRawUnitCommand_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ActionRawUnitCommand)
	// target
	switch x := m.Target.(type) {
	case *ActionRawUnitCommand_TargetWorldSpacePos:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TargetWorldSpacePos); err != nil {
			return err
		}
	case *ActionRawUnitCommand_TargetUnitTag:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.TargetUnitTag))
	case nil:
	default:
		return fmt.Errorf("ActionRawUnitCommand.Target has unexpected type %T", x)
	}
	return nil
}

func _ActionRawUnitCommand_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ActionRawUnitCommand)
	switch tag {
	case 2: // target.target_world_space_pos
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Point2D)
		err := b.DecodeMessage(msg)
		m.Target = &ActionRawUnitCommand_TargetWorldSpacePos{msg}
		return true, err
	case 3: // target.target_unit_tag
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Target = &ActionRawUnitCommand_TargetUnitTag{x}
		return true, err
	default:
		return false, nil
	}
}

func _ActionRawUnitCommand_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ActionRawUnitCommand)
	// target
	switch x := m.Target.(type) {
	case *ActionRawUnitCommand_TargetWorldSpacePos:
		s := proto.Size(x.TargetWorldSpacePos)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ActionRawUnitCommand_TargetUnitTag:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.TargetUnitTag))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ActionRawCameraMove struct {
	CenterWorldSpace *Point `protobuf:"bytes,1,opt,name=center_world_space,json=centerWorldSpace" json:"center_world_space,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ActionRawCameraMove) Reset()                    { *m = ActionRawCameraMove{} }
func (m *ActionRawCameraMove) String() string            { return proto.CompactTextString(m) }
func (*ActionRawCameraMove) ProtoMessage()               {}
func (*ActionRawCameraMove) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *ActionRawCameraMove) GetCenterWorldSpace() *Point {
	if m != nil {
		return m.CenterWorldSpace
	}
	return nil
}

type ActionRawToggleAutocast struct {
	AbilityId        *int32   `protobuf:"varint,1,opt,name=ability_id,json=abilityId" json:"ability_id,omitempty"`
	UnitTags         []uint64 `protobuf:"varint,2,rep,name=unit_tags,json=unitTags" json:"unit_tags,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ActionRawToggleAutocast) Reset()                    { *m = ActionRawToggleAutocast{} }
func (m *ActionRawToggleAutocast) String() string            { return proto.CompactTextString(m) }
func (*ActionRawToggleAutocast) ProtoMessage()               {}
func (*ActionRawToggleAutocast) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{11} }

func (m *ActionRawToggleAutocast) GetAbilityId() int32 {
	if m != nil && m.AbilityId != nil {
		return *m.AbilityId
	}
	return 0
}

func (m *ActionRawToggleAutocast) GetUnitTags() []uint64 {
	if m != nil {
		return m.UnitTags
	}
	return nil
}

type Event struct {
	DeadUnits        []uint64 `protobuf:"varint,1,rep,name=dead_units,json=deadUnits" json:"dead_units,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{12} }

func (m *Event) GetDeadUnits() []uint64 {
	if m != nil {
		return m.DeadUnits
	}
	return nil
}

func init() {
	proto.RegisterType((*StartRaw)(nil), "SC2APIProtocol.StartRaw")
	proto.RegisterType((*ObservationRaw)(nil), "SC2APIProtocol.ObservationRaw")
	proto.RegisterType((*PowerSource)(nil), "SC2APIProtocol.PowerSource")
	proto.RegisterType((*PlayerRaw)(nil), "SC2APIProtocol.PlayerRaw")
	proto.RegisterType((*UnitOrder)(nil), "SC2APIProtocol.UnitOrder")
	proto.RegisterType((*PassengerUnit)(nil), "SC2APIProtocol.PassengerUnit")
	proto.RegisterType((*Unit)(nil), "SC2APIProtocol.Unit")
	proto.RegisterType((*MapState)(nil), "SC2APIProtocol.MapState")
	proto.RegisterType((*ActionRaw)(nil), "SC2APIProtocol.ActionRaw")
	proto.RegisterType((*ActionRawUnitCommand)(nil), "SC2APIProtocol.ActionRawUnitCommand")
	proto.RegisterType((*ActionRawCameraMove)(nil), "SC2APIProtocol.ActionRawCameraMove")
	proto.RegisterType((*ActionRawToggleAutocast)(nil), "SC2APIProtocol.ActionRawToggleAutocast")
	proto.RegisterType((*Event)(nil), "SC2APIProtocol.Event")
	proto.RegisterEnum("SC2APIProtocol.DisplayType", DisplayType_name, DisplayType_value)
	proto.RegisterEnum("SC2APIProtocol.Alliance", Alliance_name, Alliance_value)
	proto.RegisterEnum("SC2APIProtocol.CloakState", CloakState_name, CloakState_value)
}

func init() { proto.RegisterFile("s2clientprotocol/raw.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 1536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x72, 0x23, 0x39,
	0x15, 0x8e, 0xed, 0xd8, 0xb1, 0x8f, 0x7f, 0x57, 0x99, 0x9f, 0x9e, 0xcc, 0x0e, 0x1b, 0x3c, 0xb0,
	0x33, 0x04, 0x98, 0x81, 0xd4, 0x42, 0x15, 0x55, 0xb0, 0x4c, 0x26, 0xd9, 0xc5, 0xae, 0xda, 0x99,
	0xb8, 0xe4, 0x2c, 0x54, 0x71, 0xd3, 0x28, 0xad, 0x93, 0xb6, 0x6a, 0xdb, 0xea, 0x46, 0x92, 0xed,
	0xf5, 0xde, 0xf2, 0x1c, 0x5c, 0xf2, 0x2e, 0xdc, 0xf3, 0x00, 0x3c, 0x08, 0x5c, 0x50, 0x52, 0xcb,
	0x7f, 0x71, 0x3c, 0xa1, 0x6a, 0xef, 0xfa, 0x7c, 0xe7, 0x3b, 0xea, 0xf3, 0xa7, 0x73, 0x04, 0x47,
	0xfa, 0x34, 0x4a, 0x04, 0x4a, 0x93, 0xa9, 0xd4, 0xa4, 0x51, 0x9a, 0xbc, 0x56, 0x6c, 0xf6, 0xca,
	0x09, 0xa4, 0x35, 0x3c, 0x3f, 0x3d, 0x1b, 0xf4, 0x07, 0x5e, 0x73, 0xf4, 0x6c, 0x8b, 0x1b, 0xa5,
	0xe3, 0x71, 0x2a, 0x73, 0x7a, 0xf7, 0x6f, 0x25, 0xa8, 0x0e, 0x0d, 0x53, 0x86, 0xb2, 0x19, 0x39,
	0x85, 0xea, 0x98, 0x65, 0xa1, 0x16, 0xdf, 0x61, 0x50, 0x38, 0x2e, 0xbc, 0xac, 0x9f, 0x3e, 0x7e,
	0xb5, 0x79, 0xdc, 0xab, 0xa1, 0xf8, 0x0e, 0x4f, 0x2f, 0xfa, 0xf4, 0x60, 0xcc, 0x32, 0xfb, 0x4d,
	0x7e, 0x0b, 0x8d, 0x8c, 0x99, 0x91, 0x90, 0x71, 0x18, 0x2b, 0xc1, 0x83, 0xa2, 0xb3, 0x7b, 0x72,
	0xdb, 0xae, 0x3f, 0x66, 0x31, 0x5e, 0x30, 0xc3, 0x68, 0xdd, 0xd3, 0xff, 0xa0, 0x04, 0x27, 0x6f,
	0xa0, 0x65, 0x50, 0x29, 0x26, 0x64, 0x38, 0x42, 0x11, 0x8f, 0x4c, 0x50, 0xba, 0xcf, 0xbe, 0xe9,
	0x0d, 0x7a, 0x8e, 0x6f, 0x4f, 0xc8, 0x12, 0x16, 0xe1, 0x18, 0xa5, 0xc9, 0x3d, 0xd8, 0xbf, 0xf7,
	0x84, 0xa5, 0x81, 0xf3, 0xe1, 0xf7, 0x60, 0x81, 0x39, 0xbb, 0x4e, 0x30, 0x64, 0x0a, 0x59, 0x50,
	0x76, 0x07, 0x1c, 0xdd, 0x3e, 0x80, 0x62, 0x64, 0x98, 0x8c, 0x13, 0xec, 0xd3, 0xc6, 0xc2, 0xe0,
	0x4c, 0x21, 0x23, 0x6f, 0xa0, 0xad, 0x6d, 0x0a, 0xc3, 0x24, 0x8d, 0x98, 0x11, 0xa9, 0xd4, 0x41,
	0xe5, 0xb8, 0x74, 0x57, 0xf6, 0x06, 0xa9, 0x90, 0xe6, 0xf4, 0x82, 0xb6, 0x1c, 0xff, 0xab, 0x05,
	0xbd, 0xfb, 0xaf, 0x02, 0xb4, 0x2e, 0xaf, 0x35, 0xaa, 0xa9, 0x03, 0x6c, 0x2d, 0x7e, 0x09, 0x15,
	0xfb, 0x13, 0x54, 0xbe, 0x12, 0x5b, 0xf1, 0x0c, 0x9c, 0x96, 0xb2, 0x19, 0xf5, 0x44, 0x72, 0x02,
	0xe5, 0x89, 0x14, 0x46, 0x07, 0x45, 0xf7, 0xf7, 0x07, 0xb7, 0x2d, 0xbe, 0x96, 0xc2, 0xd0, 0x9c,
	0x42, 0x7e, 0x05, 0x35, 0x57, 0x6a, 0xc3, 0x0c, 0xfa, 0x9c, 0x07, 0xb7, 0xf9, 0xef, 0x58, 0x36,
	0xb4, 0x7a, 0x6a, 0xbb, 0xc2, 0x7d, 0x91, 0x9f, 0x42, 0x19, 0xa7, 0x28, 0x8d, 0x4f, 0xf2, 0xc3,
	0xdb, 0x26, 0x5f, 0x58, 0x25, 0xcd, 0x39, 0xdd, 0xbf, 0x40, 0x7d, 0x90, 0xce, 0x50, 0x0d, 0xd3,
	0x89, 0x8a, 0x90, 0xbc, 0x80, 0x52, 0x96, 0x6a, 0x1f, 0xce, 0xc3, 0x3b, 0x53, 0x43, 0x2d, 0x83,
	0x3c, 0x82, 0x8a, 0x62, 0x5c, 0x4c, 0xb4, 0x6b, 0xa6, 0x22, 0xf5, 0x12, 0xe9, 0x40, 0xc9, 0xb0,
	0xd8, 0x79, 0xbb, 0x4f, 0xed, 0x67, 0xf7, 0xef, 0x05, 0xa8, 0x2d, 0xf3, 0x40, 0xde, 0x40, 0x33,
	0xb3, 0xff, 0x0b, 0xb5, 0xfb, 0xa1, 0xfd, 0x95, 0xcd, 0xc3, 0xd3, 0xed, 0x5f, 0x2d, 0x9d, 0xa2,
	0x8d, 0x6c, 0x25, 0x68, 0xf2, 0x73, 0xa8, 0x44, 0x6c, 0x8c, 0x8a, 0xf9, 0x36, 0xde, 0xe1, 0xa5,
	0x27, 0x91, 0x4f, 0xa0, 0x3e, 0xc9, 0x62, 0xc5, 0x38, 0x86, 0x82, 0xeb, 0xa0, 0x74, 0x5c, 0x7a,
	0xd9, 0xa4, 0xe0, 0xa1, 0x3e, 0xd7, 0xdd, 0x7f, 0x16, 0xa0, 0x66, 0xb3, 0x7e, 0xa9, 0x38, 0x2a,
	0xf2, 0x0c, 0x80, 0x5d, 0x8b, 0x44, 0x98, 0x79, 0x28, 0xb8, 0xcb, 0x43, 0x93, 0xd6, 0x3c, 0xd2,
	0xe7, 0xe4, 0x2b, 0x78, 0x64, 0x98, 0x8a, 0xd1, 0x84, 0xb3, 0x54, 0x25, 0x3c, 0xd4, 0x19, 0x8b,
	0x30, 0xb4, 0x29, 0xfb, 0x90, 0x33, 0xbd, 0x3d, 0x7a, 0x98, 0x9b, 0xfd, 0xc9, 0x5a, 0x0d, 0xad,
	0xd1, 0x20, 0xd5, 0xe4, 0x25, 0xb4, 0xfd, 0x69, 0xb6, 0xe0, 0xe1, 0x32, 0x71, 0xbd, 0x3d, 0xda,
	0xcc, 0x15, 0xd6, 0xb1, 0x2b, 0x16, 0x93, 0x23, 0xa8, 0x66, 0x2a, 0x8d, 0x15, 0x6a, 0xed, 0xca,
	0x5a, 0xa4, 0x4b, 0xf9, 0x6d, 0x15, 0x2a, 0x39, 0xb9, 0xfb, 0x8f, 0x02, 0x34, 0x07, 0x4c, 0x6b,
	0x94, 0x31, 0x2a, 0x6b, 0xba, 0x28, 0x47, 0x61, 0x59, 0x0e, 0x5b, 0xb8, 0x11, 0xb2, 0xc4, 0x8c,
	0x16, 0x85, 0xcb, 0x25, 0x1b, 0x78, 0xfe, 0x15, 0x8e, 0xd9, 0xb7, 0xce, 0x8d, 0x22, 0xad, 0xe5,
	0xc8, 0x3b, 0xf6, 0xad, 0x35, 0xd3, 0x23, 0x81, 0x09, 0xf7, 0xbf, 0xf7, 0x92, 0xc5, 0x51, 0xa2,
	0x8a, 0xe7, 0xee, 0x46, 0x16, 0xa9, 0x97, 0xc8, 0x53, 0xa8, 0xe5, 0x31, 0xcd, 0x33, 0x0c, 0x2a,
	0x2e, 0x8d, 0x55, 0x0b, 0x5c, 0xcd, 0x33, 0xec, 0xfe, 0xbb, 0x06, 0xfb, 0xce, 0xbd, 0xcf, 0xa1,
	0xc1, 0x85, 0xb6, 0x57, 0x23, 0x27, 0x5a, 0x3f, 0x5b, 0xdb, 0xcd, 0x70, 0x91, 0x73, 0xac, 0x2d,
	0xad, 0xf3, 0x95, 0x40, 0x3e, 0x83, 0x2a, 0x4b, 0x12, 0xc1, 0x64, 0x84, 0x2e, 0x9c, 0xd6, 0xf6,
	0x05, 0x39, 0xf3, 0x7a, 0xba, 0x64, 0x6e, 0xf7, 0xe8, 0xa6, 0xb7, 0xfb, 0x9b, 0xde, 0x92, 0x07,
	0x50, 0x4e, 0x67, 0x12, 0x95, 0x8b, 0xb0, 0x4c, 0x73, 0x61, 0x71, 0x53, 0x2a, 0xff, 0xcf, 0x4d,
	0xb9, 0x61, 0x91, 0x90, 0x71, 0x70, 0x90, 0x67, 0x28, 0x97, 0xd6, 0x6e, 0x50, 0x75, 0xe3, 0x06,
	0xfd, 0x18, 0x5a, 0xd7, 0x13, 0x91, 0xf0, 0x70, 0x59, 0xf0, 0x9a, 0xd3, 0x37, 0x1d, 0x3a, 0xf0,
	0x20, 0xf9, 0x05, 0x94, 0xa3, 0x24, 0x65, 0xdf, 0x04, 0xe0, 0xe2, 0xde, 0x9a, 0x84, 0xe7, 0x56,
	0x99, 0x8f, 0x86, 0x9c, 0x48, 0x7e, 0x08, 0x0d, 0x8e, 0x06, 0x23, 0x13, 0x2a, 0x26, 0x63, 0x0c,
	0x3e, 0x71, 0xc7, 0xd6, 0x73, 0x8c, 0x5a, 0xc8, 0x5e, 0x16, 0xc5, 0x38, 0x53, 0x9e, 0x71, 0xec,
	0x18, 0xe0, 0xa0, 0x25, 0x41, 0xe8, 0x50, 0x63, 0x82, 0x91, 0x41, 0x1e, 0xd4, 0x8f, 0x0b, 0x2f,
	0xab, 0x14, 0x84, 0x1e, 0x7a, 0x84, 0x1c, 0x43, 0x43, 0xe8, 0x30, 0x95, 0xa1, 0x8e, 0x14, 0xa2,
	0x0c, 0x1a, 0x0b, 0xc6, 0xa5, 0x1c, 0x3a, 0x84, 0x3c, 0x86, 0x03, 0xa1, 0xc3, 0xeb, 0x44, 0x64,
	0x41, 0xd3, 0x29, 0x2b, 0x42, 0xbf, 0x4d, 0x44, 0x66, 0x3b, 0x50, 0xe8, 0xd0, 0xdd, 0x75, 0xe4,
	0xc1, 0x73, 0xa7, 0xab, 0x09, 0x3d, 0xc8, 0x81, 0xb5, 0xc6, 0x6d, 0x7d, 0xa0, 0x71, 0xdb, 0xbb,
	0x1b, 0xb7, 0xb3, 0xa3, 0x71, 0x3f, 0xda, 0x68, 0xdc, 0x9f, 0x40, 0x67, 0x2c, 0x24, 0x2a, 0x96,
	0x84, 0x51, 0x2a, 0x0d, 0x4a, 0xa3, 0x03, 0xe2, 0x0a, 0xdf, 0xf6, 0xf8, 0xb9, 0x87, 0x2d, 0x75,
	0x8a, 0x3a, 0x43, 0x89, 0x2b, 0xea, 0x61, 0x4e, 0xf5, 0xf8, 0x92, 0xfa, 0x14, 0x6a, 0x42, 0x87,
	0x37, 0xc9, 0xdc, 0xf6, 0xc1, 0x03, 0x17, 0x5a, 0x55, 0xe8, 0x2f, 0x9d, 0xec, 0x93, 0x7a, 0x3d,
	0x51, 0x2a, 0x9d, 0x21, 0x0f, 0x1e, 0x2e, 0x52, 0xf6, 0xd6, 0x23, 0x76, 0xcf, 0xa4, 0x76, 0x3a,
	0xe9, 0xe0, 0x91, 0x9b, 0x96, 0x4f, 0xee, 0xda, 0x1a, 0x6e, 0x7e, 0x51, 0x4f, 0x24, 0x1f, 0x03,
	0x30, 0xce, 0x6d, 0x21, 0x6c, 0xab, 0x3f, 0x76, 0xad, 0x5e, 0x65, 0x9c, 0x5f, 0x4a, 0x3b, 0x4e,
	0x7e, 0x07, 0x90, 0x2d, 0xe6, 0x84, 0x0e, 0x02, 0x77, 0xe8, 0xb3, 0xad, 0x1e, 0x5e, 0x9f, 0x24,
	0x74, 0xcd, 0x80, 0x9c, 0xc0, 0x47, 0x11, 0x53, 0x71, 0xea, 0xc7, 0x9f, 0x61, 0xdf, 0xa0, 0x0c,
	0x9e, 0xe4, 0x91, 0x3b, 0x85, 0x9b, 0x70, 0x57, 0x16, 0x26, 0x9f, 0x42, 0x7b, 0x9d, 0x6b, 0x6b,
	0x74, 0xe4, 0x98, 0xcd, 0x15, 0xd3, 0xd6, 0xe9, 0x09, 0x54, 0xaf, 0x27, 0x37, 0x37, 0x6e, 0x48,
	0x3f, 0x75, 0x43, 0xfa, 0xc0, 0xca, 0x7d, 0xae, 0xc9, 0x6b, 0x38, 0x64, 0x5a, 0x8b, 0x58, 0x22,
	0x0f, 0x47, 0x4c, 0x4d, 0x51, 0x1b, 0xeb, 0xf6, 0xc7, 0xee, 0x18, 0xb2, 0x50, 0xf5, 0x96, 0x1a,
	0x5b, 0x18, 0xc1, 0x91, 0x25, 0xeb, 0xec, 0x67, 0xb9, 0x7b, 0x0e, 0x5f, 0xa3, 0xbe, 0x80, 0xf6,
	0x0c, 0x59, 0x96, 0xca, 0x30, 0x4a, 0xd3, 0x84, 0xa7, 0x33, 0x19, 0xfc, 0xc0, 0xf5, 0x43, 0x2b,
	0x87, 0xcf, 0x3d, 0x4a, 0x7e, 0x06, 0x04, 0x65, 0xcc, 0x62, 0xe4, 0xa1, 0x9f, 0xd9, 0x36, 0xb1,
	0x5d, 0x97, 0xd8, 0x8e, 0xd7, 0x5c, 0x39, 0xc5, 0x15, 0x8b, 0xbb, 0x53, 0xa8, 0x2e, 0x36, 0x33,
	0xf9, 0x0d, 0xc0, 0x54, 0x68, 0x91, 0xef, 0x90, 0x5d, 0x2f, 0x85, 0xd5, 0xcb, 0x67, 0x8d, 0x4c,
	0x5e, 0x43, 0xd9, 0x5e, 0x9a, 0xec, 0xfe, 0x17, 0x5b, 0xce, 0xeb, 0xfe, 0xb7, 0x00, 0xb5, 0xb3,
	0x68, 0xf1, 0x3e, 0xe9, 0x43, 0xc3, 0x8d, 0x35, 0xfb, 0x9a, 0x64, 0x92, 0xfb, 0x7f, 0xff, 0x68,
	0x6b, 0x44, 0x2e, 0x0c, 0x6c, 0xa1, 0xcf, 0x73, 0x6e, 0x6f, 0x8f, 0xd6, 0x27, 0x2b, 0x91, 0x7c,
	0x09, 0xf5, 0x7c, 0xa1, 0x86, 0xe3, 0x74, 0x8a, 0xde, 0x9f, 0xe7, 0x3b, 0x4f, 0x3a, 0x77, 0xdc,
	0x77, 0xe9, 0x14, 0x7b, 0x7b, 0x14, 0xa2, 0xa5, 0x44, 0x28, 0xb4, 0x4d, 0x1a, 0xc7, 0xf6, 0x19,
	0x37, 0x31, 0x69, 0xc4, 0xf4, 0xe2, 0x35, 0xf9, 0x62, 0xe7, 0x59, 0x57, 0x8e, 0x7f, 0xe6, 0xe9,
	0xbd, 0x3d, 0xda, 0x32, 0x1b, 0x88, 0x5d, 0x80, 0xcc, 0x91, 0xbb, 0xff, 0x29, 0xc0, 0x83, 0xbb,
	0xa2, 0xb9, 0x63, 0xad, 0x97, 0xd7, 0xd7, 0xfa, 0xfb, 0x7b, 0xd6, 0xfa, 0xae, 0x47, 0xe2, 0xf7,
	0x5f, 0xec, 0xcb, 0xcd, 0xc3, 0x62, 0xbb, 0xd9, 0x4b, 0xf6, 0x9a, 0x4e, 0x72, 0x9d, 0x26, 0xcf,
	0xa1, 0xf9, 0xd7, 0x09, 0x4e, 0x70, 0x59, 0xc0, 0xb2, 0x1b, 0x0d, 0x0d, 0x07, 0xfa, 0xd0, 0xd6,
	0xd6, 0xff, 0x9f, 0xe1, 0xf0, 0x8e, 0x02, 0x90, 0x73, 0x20, 0x11, 0x4a, 0x83, 0x6a, 0x3d, 0xb8,
	0x0f, 0x3f, 0xf1, 0x3a, 0xb9, 0xc1, 0x2a, 0xa8, 0xee, 0xd7, 0xf0, 0x78, 0x47, 0x41, 0xee, 0xcb,
	0xed, 0x46, 0x84, 0xc5, 0xcd, 0x08, 0xbb, 0x9f, 0x42, 0xd9, 0x3d, 0x47, 0xed, 0x21, 0x1c, 0x19,
	0x0f, 0xf3, 0xc7, 0x71, 0xc1, 0xd1, 0x6a, 0x16, 0xb1, 0x89, 0xd2, 0x27, 0x9f, 0x41, 0x7d, 0xed,
	0x11, 0x40, 0xea, 0x70, 0xf0, 0x47, 0x7b, 0x4b, 0x12, 0xec, 0x14, 0x48, 0x03, 0xaa, 0x43, 0xc9,
	0x32, 0x3d, 0x4a, 0x4d, 0xa7, 0x48, 0x00, 0x2a, 0x3d, 0xc1, 0x39, 0xca, 0x4e, 0xe9, 0xe4, 0xd7,
	0x50, 0x5d, 0xac, 0x7f, 0x52, 0x85, 0xfd, 0x21, 0x26, 0x37, 0x9d, 0x82, 0xfd, 0x3a, 0x4b, 0x92,
	0x79, 0xa7, 0x68, 0x8f, 0x79, 0x8f, 0x13, 0xa3, 0x58, 0xd2, 0x29, 0x91, 0x1a, 0x94, 0xbf, 0x90,
	0x38, 0x9e, 0x77, 0xf6, 0x4f, 0x3e, 0x07, 0x58, 0xad, 0x4f, 0xcb, 0x72, 0x12, 0xf2, 0x4e, 0x81,
	0x1c, 0x42, 0xdb, 0x0b, 0x17, 0x6e, 0x6f, 0x22, 0xef, 0x14, 0x49, 0x0b, 0xe0, 0x7d, 0x6a, 0x16,
	0xa4, 0xd2, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x67, 0x55, 0xe5, 0xfc, 0x0d, 0x00, 0x00,
}
